export const API_ENDPOINTS = {
  ORGANIZATIONS_GET: `organizations/`,
  MEMBERSHIP_REQUESTS_ALL_GET: `organizations/membership-requests`,
  INVITE_AUDIENCES_BY_ORGANIZATION_ID_POST: `organizations/{{organizationId}}/audiences/invitations`,
  INVITED_AUDIENCES_BY_ORGANIZATION_ID_GET: `organizations/{{organizationId}}/audiences/invitations`,
  DELETE_AUDIENCE_INVITATION: `organizations/{{organizationId}}/audiences/invitations/{{invitationId}}`,
  AUDIENCES_BY_ORGANIZATION_ID_GET: `organizations/{{organizationId}}/audiences`,
  CHANGE_AUDIENCE_ROLE_IN_ORGANIZATION_PATCH: `organizations/{{organizationId}}/audiences`,
  DELETE_AUDIENCE_FROM_ORGANIZATION_ACCESS: `organizations/{{organizationId}}/audiences`,
  MEMBERSHIP_REQUESTS_BY_ORGANIZATION_ID_GET: `organizations/{{organizationId}}/requests`,
  ORGANIZATIONS_REGISTER_POST: `organizations/register`,
  ORGANIZATIONS_PROVISION_POST: `organizations/{{organizationId}}/provision`,

  // Auth
  AUTH_INITIATE_LOGIN_FLOW_GET: `auth/relay/self-service/login/browser`,
  AUTH_INITIATE_LOGOUT_FLOW_GET: `auth/relay/self-service/logout/browser`,
  AUTH_INITIAL_LOGIN_FLOW_BY_EMAIL_POST: `auth/login/flow/create`,
  USER_WHOAMI_GET: 'auth/whoami',
  USER_CHECK_USERNAME_GET: 'users/check-username',

  // Onboarding
  ONBOARDING_APPROVAL_POST: 'onboarding/user/waitlist-check',
  ONBOARDING_USER_PROFILE_PATCH: 'onboarding/user/profile',
  ONBOARDING_ORG_SETUP_POST: 'onboarding/org/setup',
  ONBOARDING_PROVISIONING_POST: 'onboarding/org/provision',
  ONBOARDING_SKIP_POST: 'onboarding/user/bypass-onboarding',
  ONBOARDING_UPLOAD_URL_POST: 'onboarding/assets/upload-url',

  AUTH_BASE_URL_GET: `auth/api-base-url`,
  AUTH_ERROR_DETAILS_GET: `auth/relay/internal/self-service/errors`,
  TEAMS_BY_ORGANIZATION_ID_GET: `organizations/{{organizationId}}/teams`,
  USER_TEAMS_BY_ORGANIZATION_ID_GET: `organizations/{{organizationId}}/team-members`,
  TEAMS_BY_ORGANIZATION_ID_POST: `organizations/{{organizationId}}/teams`,
  ALL_TEAMS_BY_TEAM_ID_GET: `organizations/{{organizationId}}/teams/{{teamId}}`,
  ADD_TEAMS_TO_AUDIENCE_POST: `organizations/{{organizationId}}/teams/{{teamId}}/add`,
  REMOVE_TEAMS_FROM_AUDIENCE_POST: `organizations/{{organizationId}}/teams/{{teamId}}/remove`,
  TEAMS_BY_ORGANIZATION_ID_PATCH: `organizations/{{organizationId}}/teams/{{teamId}}`,
  TEAMS_BY_ORGANIZATION_ID_DELETE: `organizations/{{organizationId}}/teams/{{teamId}}`,

  // feedback
  FEEDBACKS_GET: `feedbacks`,
  FEEDBACKS_ARCHIVE_POST: `feedbacks/archive`,
  FEEDBACKS_OPEN_GET: `v2/conversations/open/{{processId}}`,
  FEEDBACKS_DELETE_POST: `feedbacks/delete`,
  FEEDBACKS_CONVERSATION_DELETE: `conversations/{{conversationId}}/{{resourceType}}/{{resourceId}}`,
  FEEDBACKS_UN_ARCHIVE_POST: `feedbacks/unarchive`,
  FEEDBACKS_APPLY_POST: `feedbacks/apply`,
  FEEDBACKS_STOP_PROCESSING_POST: `feedbacks/stop-processing`,

  TEAM_PENDING_APPROVALS_GET: `access-control/pending/users-access-approvals`,
  TEAM_PENDING_APPROVALS_BY_RESOURCE_ID_GET: `access-control/pending/resource-audience-policy`,

  DATASET_FILTER_CONFIG_GET: `datasets/{{datasetId}}/filter-config`,
  DATASET_DATA_GET: `datasets/{{datasetId}}/data`,
  DATASET_EXPORT_GET: `datasets/{{datasetId}}/export`,
  DATASET_DRILLDOWN_GET: `datasets/{{datasetId}}/drill-down/row/{{rowId}}`,
  DATASET_LISTING_GET: `datasets/listing`,
  AUDIENCES_BY_DATASET_ID_GET: `datasets/{{datasetId}}/audiences`,
  SHARE_DATASET_TO_AUDIENCES_BY_DATASET_ID_POST: `datasets/{{datasetId}}/audiences`,
  DATASET_UPDATE_POST: `datasets/{{datasetId}}/update-data`,
  DATASET_ACTION_STATUS_GET: `datasets/{{datasetId}}/actions`,
  DATASET_EXPORTS_SIGNED_URL_GET: `datasets/{{datasetId}}/signed-url/{{workflowId}}`,
  CHANGE_AUDIENCE_ROLE_IN_DATASET_PATCH: `datasets/{{datasetId}}/audiences`,
  DELETE_AUDIENCE_FROM_DATASET_ACCESS: `datasets/{{datasetId}}/audiences`,
  DATASET_RULES_LISTING_GET: `datasets/rules/listing`,
  DATASET_FILE_IMPORT_HISTORY_GET: `datasets/{{datasetId}}/file-imports/history`,
  DATASET_ALL_GET: `/datasets/listing-all`,
  DATASET_UPDATE_PATCH: `/datasets/{{datasetId}}/update`,

  // file-import
  DATASET_SIGNED_UPLOAD_URL_POST: `datasets/file-imports/init`,
  DATASET_FILE_IMPORTS_ACTION_ID: `datasets/file-imports/{{file_upload_id}}`,
  DATASET_FILE_IMPORTS_PREVIEW_TRANSFORMATION_GET: `datasets/file-imports/{{file_upload_id}}/preview`,
  DATASET_FILE_IMPORTS_PREVIEW_TRANSFORMATION_CONFIRM_POST: `datasets/file-imports/{{file_upload_id}}/confirm`,

  DATASET_RULES_BY_RULE_IDS_GET: `datasets/rules/ids`,
  DATASET_RULES_PRIORITY_PATCH: `datasets/rules/priority`,
  DATASET_RULE_DELETE: `datasets/rules/{{ruleId}}`,
  WIDGET_INSTANCE_GET: `widgets/{{widgetId}}/instance`,
  WIDGET_DATA_GET: `widgets/{{widgetId}}/data`,
  WIDGET_DELETE: `widgets/{{widgetId}}`,
  WIDGET_INSTANCE_POST: `widgets/instance`,
  WIDGET_INSTANCE_UPDATE_PUT: `widgets/{{widgetId}}`,

  PAGES_GET: `pages/get-pages`,
  PAGES_SHEETS_GET: `pages/{{pageId}}`,
  PAGES_SHEETS_SHEET_GET: `pages/{{pageId}}/sheets/{{sheetId}}`,
  PAGES_SHEETS_FILTER_CONFIG_GET: `pages/{{pageId}}/sheets/{{sheetId}}/filters`,
  AUDIENCES_BY_PAGE_ID_GET: `pages/{{pageId}}/audiences`,
  SHARE_PAGE_TO_AUDIENCES_BY_PAGE_ID_POST: `pages/{{pageId}}/audiences`,
  CHANGE_AUDIENCE_ROLE_IN_PAGE_PATCH: `pages/{{pageId}}/audiences`,
  DELETE_AUDIENCE_FROM_PAGE_ACCESS: `pages/{{pageId}}/audiences`,
  UPDATE_PAGE_INDEXES: `pages/update-indexes`,
  UPDATE_SHEET_INDEXES: `pages/{{pageId}}/sheets/update-indexes`,
  UPDATE_PAGE: `pages/{{pageId}}`,
  DELETE_PAGE: `pages/{{pageId}}`,
  UPDATE_SHEET_BY_PAGE_ID: `pages/{{pageId}}/sheets/{{sheetId}}`,
  DELETE_SHEET_BY_PAGE_ID: `pages/{{pageId}}/sheets/{{sheetId}}`,
  UPDATE_SHEET_LAYOUT_PUT: `pages/{{pageId}}/sheets/{{sheetId}}/update-layout`,
  SHEET_CREATE_POST: `pages/{{pageId}}/sheets/`,
  PAGES_CREATE_POST: `pages/`,
  PAGES_SHEETS_FILTER_CONFIG_POST: `pages/{{pageId}}/sheets/{{sheetId}}/filters`,
  PAGES_SHEETS_FILTER_CONFIG_PATCH: `pages/{{pageId}}/sheets/{{sheetId}}/filters/{{filterId}}`,
  PAGES_SHEETS_FILTER_CONFIG_DELETE: `pages/{{pageId}}/sheets/{{sheetId}}/filters/{{filterId}}`,

  PAYMENTS_SOURCE_ACCOUNTS_GET: `payments/source-accounts`,
  PAYMENTS_DESTINATION_ACCOUNTS_GET: `payments/destination-accounts`,
  PAYMENTS_TEMPLATE_LIST_GET: `payments/templates/`,
  PAYMENTS_TEMPLATE_CREATE_POST: `payments/templates/`,
  PAYMENTS_RECIPIENT_BY_SOURCE_ACCOUNT_GET: `payments/recipients`,
  PAYMENTS_INITIATE_PAYMENT_POST: `payments/`,
  PAYMENTS_CONFIG_GET: `payments/config`,
  PAYMENTS_APPROVALS_INFO_GET: `payments/{{paymentId}}/approvals-info`,
  PAYMENTS_TEMPLATE_APPROVALS_INFO_GET: `payments/templates/{{templateId}}/approvals-info`,
  FORMS_SIGNED_UPLOAD_URL_POST: `file-imports/initiate`,
  FORMS_SIGNED_UPLOAD_ACK_POST: `file-imports/{{fileImportId}}/acknowledge`,
  DOWNLOAD_FILE_GET: `file-imports/{{fileImportId}}/download-url`,
  PAYMENTS_AUDIENCES_GET: `payments/audiences`,

  APPROVAL_ACTION_POST: '/approval/action',

  PAYMENT_LIST_FILTER_CONFIG_GET: `payments/filter-config`,
  PAYMENT_LIST_GET: `payments/`,
  PAYMENT_DETAILS_GET: `payments/{{paymentId}}`,
  PAYMENTS_ACCOUNTS_GET: `payments/accounts`,
  PAYMENTS_ACCOUNT_FILTER_CONFIG_GET: `payments/accounts/filter-config`,
  RECIPIENT_LIST_GET: `recipients/filtered-accounts`,
  RECIPIENT_CREATE_POST: `recipients/{{recipientId}}/create-recipient-and-account`,
  RECIPIENT_ACCOUNT_CREATE_POST: `recipients/account`,

  USER_INVITATIONS_GET: `/organizations/invitations`,
  ACCEPT_INVITATION_POST: `/organizations/invitations/{{invitationId}}/accept`,
  POLICY_LIST_GET: `/policy/list`,
  POLICY_PENDING_APPROVALS_GET: `/policy/pending-approvals`,
  POLICY_RESULT_APPROVALS_GET: `/policy-result/{{policyResultId}}/approvals`,
  POLICY_APPROVE_POST: `/approval/approve`,
  POLICY_REJECT_POST: `/approval/reject`,

  // v1 endpoints -->
  RESOURCE_AUDIENCES_BY_RESOURCE_ID_GET: `{{resourceRoute}}/{{resourceId}}/audiences`,
  SHARE_RESOURCE_TO_AUDIENCES_POST: `{{resourceRoute}}/{{resourceId}}/audiences`,
  CHANGE_AUDIENCE_ROLE_IN_RESOURCE_PATCH: `{{resourceRoute}}/{{resourceId}}/audiences`,
  DELETE_RESOURCE_FROM_AUDIENCES: `{{resourceRoute}}/{{resourceId}}/audiences`,
  // v2 endpoints -->
  RESOURCE_AUDIENCES_BY_RESOURCE_ID_GET_V2: `access-control/{{resourceRoute}}/{{resourceId}}/audiences`,
  SHARE_RESOURCE_TO_AUDIENCES_POST_V2: `access-control/{{resourceRoute}}/{{resourceId}}/audiences`,
  CHANGE_AUDIENCE_ROLE_IN_RESOURCE_PATCH_V2: `access-control/{{resourceRoute}}/{{resourceId}}/audiences`,
  DELETE_RESOURCE_FROM_AUDIENCES_V2: `access-control/{{resourceRoute}}/{{resourceId}}/audiences`,

  FORMS_CONFIG_GET: `v1/forms/config`,
  FORMS_SUBMIT: `v1/forms/submissions`,

  POLICY_CREATE_POST: '/policy',
  POLICY_UPDATE_POST: '/policy/{{policyId}}',
  POLICY_CREATE_POST_PAYMENTS: '/payments/policy',
  POLICY_UPDATE_POST_PAYMENTS: '/payments/policy/{{policyId}}',
  POLICIES_GET: '/policy/list',
  POLICY_DELETE: '/policy/{{policyId}}',

  // processes
  PROCESSES_GET: `processes/`,
  ACTIVITY_RUNS_FILTER_CONFIG_GET: `processes/{{processId}}/activity-runs/filter-config`,
  ACTIVITY_RUNS_SUMMARY_GET: `processes/{{processId}}/activity-runs/status-summary`,
  ACTIVITY_RUNS_GET: `processes/{{processId}}/activity-runs`,
  KNOWLEDGE_BASE_GET: `processes/{{processId}}/knowledge-base`,
  ACTIVITY_ARTIFACTS_GET: `processes/{{processId}}/activity-runs/{{activityRunId}}/artifacts`,
  UPDATE_ARTIFACT_PATCH: `processes/{{processId}}/artifacts/{{artifactId}}`,
  ACTIVITY_RUN_LOGS_GET: `processes/{{processId}}/activity-logs/{{activityRunId}}/logs`,
  EMIT_ACTIVITY_LOGS_POST: `processes/{{processId}}/activity-runs/{{activityRunId}}/agent-feedback`,
  ACTIVITY_SUMMARY_GET: `processes/{{processId}}/activity-runs/{{activityRunId}}/summary`,
  ACTIVITY_ARTIFACTS_BY_ARTIFACT_ID_GET: `processes/{{processId}}/activity-runs/artifacts`,
  ACTIVITY_SIGNED_URL_BY_FILE_ID_GET: `processes/{{processId}}/artifacts/{{artifactId}}/signed-url/{{fileId}}`,
  DATASET_ARTIFACTS_GET: `processes/{{processId}}/activity-runs/{{activityRunId}}/datasets/{{datasetId}}/data`,
  EMIT_HITL_ACTION_POST: `processes/{{processId}}/activity-runs/{{activityRunId}}/hitl/actions`,
  ACTIVITY_REPROCESSING_EVENTS_GET: `processes/{{processId}}/activity-runs/{{activityRunId}}/reprocessing-events`,
  PROCESSES_EVENTS_GET: `processes/events/{{activityId}}`,
  STOP_PROCESS_BUILDING_POST: `processes/{{processId}}/build-stop`,
  UNIFIED_SSE: `events`,
  ACTIVITY_RUN_DELETE: `processes/{{processId}}/activity-runs/{{activityRunId}}`,

  //Voice Agents
  SPEECH_TO_TEXT_ACCESS_TOKEN_GET: `/speech-to-text/generate-access-token`,

  INTERACTION_POST: `/v2/conversations/{{conversationId}}/messages/{{messageId}}/interactions`,
  INTERACTION_DISABLE_POST: `/v2/conversations/{{conversationId}}/messages/{{messageId}}/interactions/disable`,

  // MACS
  CONVERSATION_HISTORY_GET: `v4/conversations`,
  // Skills
  SKILLS_LIST_GET: `skills`,
  SKILLS_UPLOAD_POST: `skills`,
  SKILLS_GET_BY_ID: `skills/{{skillId}}`,
  SKILLS_UPDATE_PUT: `skills/{{skillId}}`,
  SKILLS_STATUS_PATCH: `skills/{{skillId}}/status`,
  SKILLS_DELETE: `skills/{{skillId}}`,
  // Conversations V4
  CREATE_CONVERSATION_V4: `v4/conversations`,
  POST_MESSAGE_V4: `v4/conversations/{{conversationId}}/messages`,
  LIST_CHAT_MODELS: `v3/conversations/models`,
  // Conversations V2
  FILTER_CONVERSATIONS_V2_GET: `v2/conversations/filter`,

  //TASKS
  TASKS_MESSAGES_GET: `tasks/{{conversationId}}/messages`,

  // Integrations
  INTEGRATIONS_AUTHENTICATE: `/integrations/authenticate`,
  PROCESS_CONNECTION_MAPPINGS_POST: `process/{{process_id}}/connections`,
  PROCESS_CONNECTION_MAPPINGS_GET: `process/{{process_id}}/connections`,
  GET_CONNECTION_BY_INTEGRATION_NAME: `connections/by-integration/{{integration_name}}`,
  DELETE_PROCESS_CONNECTION_MAPPING: `process/{{process_id}}/connections`,
  PROCESS_CONNECTIONS_BULK_POST: `process/{{process_id}}/connections/bulk`,
  PROCESS_CONNECTION_MODES_GET: `process/{{process_id}}/connections/modes`,
  PROCESS_CONNECTION_MODES_BULK_POST: `process/{{process_id}}/connections/modes/bulk`,

  // Trigger Subscriptions
  TRIGGER_SUBSCRIPTIONS_POST: `trigger-subscriptions`,
  TRIGGER_SUBSCRIPTIONS_GET_BY_ID: `trigger-subscriptions/{{subscription_id}}`,
  TRIGGER_SUBSCRIPTIONS_GET: `trigger-subscriptions`,
  TRIGGER_SUBSCRIPTIONS_DELETE: `trigger-subscriptions/{{subscription_id}}`,
  // Update Conversation Title
  UPDATE_CONVERSATION_TITLE: `v4/conversations/{{conversationId}}/title`,

  //INTEGRATIONS
  INTEGRATIONS_CATALOG_GET: `integrations/catalog`,
  INTEGRATIONS_CATALOG_ENABLED_GET: `integrations/catalog/enabled`,
  INTEGRATIONS_CONNECTIONS_DELETE: `integrations/connections/{{connectionId}}`,
  INTEGRATIONS_AUTHENTICATE_V2_POST: `integrations/authenticate`,
  // Filesystem API
  FILESYSTEM_STATUS_GET: `filesystem/status`,
  FILES_LIST_GET: `files`,
  FILES_CREATE_PUT: `files/{{path}}`,
  FILES_WRITE_POST: `files/{{path}}`,
  FILES_READ_GET: `files/{{path}}`,
  FILES_COPY_POST: `files/copy`,
  FILES_MOVE_POST: `files/move`,
  FILES_DELETE: `files/{{path}}`,
  FILES_UPLOAD_POST: `files/upload`,
  FILES_UPLOAD_INIT_POST: `files/upload/init`,
  FILES_UPLOAD_CHUNK_POST: `files/upload/chunk`,
  FILES_UPLOAD_COMPLETE_POST: `files/upload/complete`,
  FILES_UPLOAD_CANCEL_DELETE: `files/upload/{{upload_id}}`,
};
