FROM node:20-alpine

WORKDIR /app

# Ensure container's Node.js is used
ENV PATH /usr/local/bin:$PATH
ENV NODE_ENV=development
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 2000

# Use container's node to run npm
CMD ["/usr/local/bin/node", "/app/node_modules/.bin/next", "dev", "-p", "2000"]