FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1
ENV PATH /app/node_modules/.bin:$PATH

COPY . .

# We don't copy or install anything - all files including node_modules 
# will be mounted during build phase

EXPOSE 4000

CMD ["npm", "run", "start:coder"]