export const PROCESS_BUILDING_ANIMATION = {
  v: '5.12.1',
  fr: 60,
  ip: 48,
  op: 173,
  w: 1080,
  h: 1080,
  nm: 'Comp 1',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: 'Frame 1410126721 1',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [540, 540, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 0,
                k: [720, 465],
                ix: 2,
              },
              p: {
                a: 0,
                k: [0, 0],
                ix: 3,
              },
              r: {
                a: 0,
                k: 36,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.921568632126, 0.921568632126, 0.921568632126, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 100,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3.9,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 18,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 18,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Frame 1410126721',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: 'Arrow',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [264, 688.5, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ind: 0,
              ty: 'sh',
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  v: [
                    [8, -12],
                    [20, 0],
                    [8, 12],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: 'Path 1',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ind: 1,
              ty: 'sh',
              ix: 2,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  v: [
                    [-8, 12],
                    [-20, 0],
                    [-8, -12],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: 'Path 2',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.145098045468, 0.274509817362, 0.960784316063, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 100,
                ix: 4,
              },
              w: {
                a: 0,
                k: 4,
                ix: 5,
              },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Icon',
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: 'Arrow Base',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [264, 688.5, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 0,
                k: [96, 96],
                ix: 2,
              },
              p: {
                a: 0,
                k: [0, 0],
                ix: 3,
              },
              r: {
                a: 0,
                k: 257.561,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 100,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [1, 1, 1, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 100,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Frame 1410126722',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 4,
      ty: 4,
      nm: 'Gradient Upper',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [540, 394.5, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 0,
                k: [720, 174],
                ix: 2,
              },
              p: {
                a: 0,
                k: [0, 0],
                ix: 3,
              },
              r: {
                a: 0,
                k: 36.9,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'gf',
              o: {
                a: 0,
                k: 100,
                ix: 10,
              },
              r: 1,
              bm: 0,
              g: {
                p: 3,
                k: {
                  a: 0,
                  k: [
                    0.844, 0.98, 0.98, 0.98, 0.922, 0.98, 0.98, 0.98, 1, 0.98, 0.98, 0.98, 0.844, 1, 0.922, 0.5, 1, 0,
                  ],
                  ix: 9,
                },
              },
              s: {
                a: 0,
                k: [1.457, -87],
                ix: 5,
              },
              e: {
                a: 0,
                k: [1.457, 61.537],
                ix: 6,
              },
              t: 1,
              nm: 'Gradient Fill 1',
              mn: 'ADBE Vector Graphic - G-Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7965',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 5,
      ty: 4,
      nm: 'Gradient Lower',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [540, 685.5, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, -100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 0,
                k: [720, 174],
                ix: 2,
              },
              p: {
                a: 0,
                k: [0, 0],
                ix: 3,
              },
              r: {
                a: 0,
                k: 36.9,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'gf',
              o: {
                a: 0,
                k: 100,
                ix: 10,
              },
              r: 1,
              bm: 0,
              g: {
                p: 3,
                k: {
                  a: 0,
                  k: [
                    0.256, 0.98, 0.98, 0.98, 0.628, 0.98, 0.98, 0.98, 1, 0.98, 0.98, 0.98, 0.256, 1, 0.628, 0.5, 1, 0,
                  ],
                  ix: 9,
                },
              },
              s: {
                a: 0,
                k: [1.457, -87],
                ix: 5,
              },
              e: {
                a: 0,
                k: [1.457, 61.537],
                ix: 6,
              },
              t: 1,
              nm: 'Gradient Fill 1',
              mn: 'ADBE Vector Graphic - G-Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7966',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 6,
      ty: 3,
      nm: 'NULL',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 0,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 1,
          k: [
            {
              i: {
                x: 0.667,
                y: 0.81,
              },
              o: {
                x: 0.333,
                y: 0,
              },
              t: 0,
              s: [453, 1156.3, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              i: {
                x: 0.138,
                y: 0.568,
              },
              o: {
                x: 0.333,
                y: 0.167,
              },
              t: 48,
              s: [453, 1021.3, 0],
              to: [0, 0, 0],
              ti: [0, 0, 0],
            },
            {
              t: 173,
              s: [453, 621, 0],
            },
          ],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [50, 50, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      ip: 0,
      op: 304,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 7,
      ty: 4,
      nm: 'Rectangle 7969',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [-22, -112, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.306, 0.306],
                      y: [0.798, 1],
                    },
                    o: {
                      x: [0.431, 0.431],
                      y: [0, 0],
                    },
                    t: 78,
                    s: [0, 45],
                  },
                  {
                    i: {
                      x: [0.557, 0.557],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.238, 0.238],
                      y: [1.026, 0],
                    },
                    t: 99,
                    s: [218.945, 45],
                  },
                  {
                    t: 146,
                    s: [252, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.306,
                      y: 0.759,
                    },
                    o: {
                      x: 0.431,
                      y: 0,
                    },
                    t: 78,
                    s: [-126, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    i: {
                      x: 0.557,
                      y: 1,
                    },
                    o: {
                      x: 0.194,
                      y: 1,
                    },
                    t: 99,
                    s: [-16.527, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 146,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7960',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 78,
      op: 382,
      st: 78,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 8,
      ty: 4,
      nm: 'Rectangle 7968',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [122, -31, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.1, 0.1],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.3, 0.3],
                      y: [0, 0],
                    },
                    t: 97.332,
                    s: [0, 45],
                  },
                  {
                    t: 136.33203125,
                    s: [540, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.1,
                      y: 1,
                    },
                    o: {
                      x: 0.3,
                      y: 0,
                    },
                    t: 97.332,
                    s: [-270, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 136.33203125,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7961',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 97,
      op: 391,
      st: 87,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 9,
      ty: 4,
      nm: 'Rectangle 7967',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [62, 50, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.1, 0.1],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.3, 0.3],
                      y: [0, 0],
                    },
                    t: 112.668,
                    s: [0, 45],
                  },
                  {
                    t: 151.66796875,
                    s: [420, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.1,
                      y: 1,
                    },
                    o: {
                      x: 0.3,
                      y: 0,
                    },
                    t: 112.668,
                    s: [-210, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 151.66796875,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7962',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 112,
      op: 396,
      st: 92,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 10,
      ty: 4,
      nm: 'Rectangle 7966',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [27.5, 131, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.1, 0.1],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.3, 0.3],
                      y: [0, 0],
                    },
                    t: 150,
                    s: [0, 45],
                  },
                  {
                    t: 189,
                    s: [351, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.1,
                      y: 1,
                    },
                    o: {
                      x: 0.3,
                      y: 0,
                    },
                    t: 150,
                    s: [-175.5, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 189,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7963',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 150,
      op: 404,
      st: 100,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 11,
      ty: 4,
      nm: 'Rectangle 7964',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [78.5, -188.3, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.1, 0.1],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.3, 0.3],
                      y: [0, 0],
                    },
                    t: 65,
                    s: [0, 45],
                  },
                  {
                    t: 104,
                    s: [453, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.1,
                      y: 1,
                    },
                    o: {
                      x: 0.3,
                      y: 0,
                    },
                    t: 65,
                    s: [-226.5, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 104,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7964',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 65,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 13,
      ty: 4,
      nm: 'Rectangle 7960',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [-22, -512.3, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.02, 0.02],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.001, 0.001],
                      y: [0, 0],
                    },
                    t: -23,
                    s: [0, 45],
                  },
                  {
                    t: 16,
                    s: [252, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.02,
                      y: 1,
                    },
                    o: {
                      x: 0.001,
                      y: 0,
                    },
                    t: -23,
                    s: [-126, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 16,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7960',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: -23,
      op: 80,
      st: -23,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 14,
      ty: 4,
      nm: 'Rectangle 7961',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [122, -431.3, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.02, 0.02],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.001, 0.001],
                      y: [0, 0],
                    },
                    t: -9.668,
                    s: [0, 45],
                  },
                  {
                    t: 29.33203125,
                    s: [540, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.02,
                      y: 1,
                    },
                    o: {
                      x: 0.001,
                      y: 0,
                    },
                    t: -9.668,
                    s: [-270, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 29.33203125,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7961',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: -20,
      op: 94,
      st: -20,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 15,
      ty: 4,
      nm: 'Rectangle 7962',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [62, -350.3, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.02, 0.02],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.001, 0.001],
                      y: [0, 0],
                    },
                    t: -2.332,
                    s: [0, 45],
                  },
                  {
                    t: 36.66796875,
                    s: [420, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.02,
                      y: 1,
                    },
                    o: {
                      x: 0.001,
                      y: 0,
                    },
                    t: -2.332,
                    s: [-210, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 36.66796875,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7962',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: -23,
      op: 114,
      st: -23,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 16,
      ty: 4,
      nm: 'Rectangle 7963',
      parent: 6,
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [27.5, -269.3, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 1,
                k: [
                  {
                    i: {
                      x: [0.1, 0.1],
                      y: [1, 1],
                    },
                    o: {
                      x: [0.3, 0.3],
                      y: [0, 0],
                    },
                    t: 25,
                    s: [0, 45],
                  },
                  {
                    t: 64,
                    s: [351, 45],
                  },
                ],
                ix: 2,
              },
              p: {
                a: 1,
                k: [
                  {
                    i: {
                      x: 0.1,
                      y: 1,
                    },
                    o: {
                      x: 0.3,
                      y: 0,
                    },
                    t: 25,
                    s: [-175.5, 0],
                    to: [0, 0],
                    ti: [0, 0],
                  },
                  {
                    t: 64,
                    s: [0, 0],
                  },
                ],
                ix: 3,
              },
              r: {
                a: 0,
                k: 15,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'st',
              c: {
                a: 0,
                k: [0.78823530674, 0.78823530674, 0.78823530674, 1],
                ix: 3,
              },
              o: {
                a: 0,
                k: 30,
                ix: 4,
              },
              w: {
                a: 0,
                k: 3,
                ix: 5,
              },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              d: [
                {
                  n: 'd',
                  nm: 'dash',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 1,
                  },
                },
                {
                  n: 'g',
                  nm: 'gap',
                  v: {
                    a: 0,
                    k: 10,
                    ix: 2,
                  },
                },
                {
                  n: 'o',
                  nm: 'offset',
                  v: {
                    a: 0,
                    k: 0,
                    ix: 7,
                  },
                },
              ],
              nm: 'Stroke 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'op',
              nm: 'Stroke align: Inside',
              a: {
                a: 0,
                k: 10,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = $bm_div($bm_neg(thisProperty.propertyGroup(2)(thisProperty.propertyGroup(1).propertyIndex - 1)('ADBE Vector Stroke Width')), 2);",
              },
              lj: 1,
              ml: {
                a: 0,
                k: 4,
                ix: 3,
              },
              ix: 3,
              mn: 'ADBE Vector Filter - Offset',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.949019610882, 0.949019610882, 0.949019610882, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 90,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 7963',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: -23,
      op: 145,
      st: -23,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 17,
      ty: 4,
      nm: 'Frame 1410126721 2',
      sr: 1,
      ks: {
        o: {
          a: 0,
          k: 100,
          ix: 11,
        },
        r: {
          a: 0,
          k: 0,
          ix: 10,
        },
        p: {
          a: 0,
          k: [540, 540, 0],
          ix: 2,
          l: 2,
        },
        a: {
          a: 0,
          k: [0, 0, 0],
          ix: 1,
          l: 2,
        },
        s: {
          a: 0,
          k: [100, 100, 100],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: {
                a: 0,
                k: [720, 465],
                ix: 2,
              },
              p: {
                a: 0,
                k: [0, 0],
                ix: 3,
              },
              r: {
                a: 0,
                k: 36,
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.980392158031, 0.980392158031, 0.980392158031, 1],
                ix: 4,
              },
              o: {
                a: 0,
                k: 100,
                ix: 5,
              },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: {
                a: 0,
                k: [0, 0],
                ix: 2,
              },
              a: {
                a: 0,
                k: [0, 0],
                ix: 1,
              },
              s: {
                a: 0,
                k: [100, 100],
                ix: 3,
              },
              r: {
                a: 0,
                k: 0,
                ix: 6,
              },
              o: {
                a: 0,
                k: 100,
                ix: 7,
              },
              sk: {
                a: 0,
                k: 0,
                ix: 4,
              },
              sa: {
                a: 0,
                k: 0,
                ix: 5,
              },
              nm: 'Transform',
            },
          ],
          nm: 'Frame 1410126721',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 304,
      st: 0,
      ct: 1,
      bm: 0,
    },
  ],
  markers: [],
  props: {},
};
