/* eslint-disable no-unused-vars */
export const enum ICON_SPRITE_TYPES {
  ALERTS_AND_FEEDBACK = 'alerts-and-feedbacks',
  ARROWS = 'arrows',
  CHARTS = 'charts',
  COMMUNICATION = 'communication',
  COUNTRY_SET_1 = 'country-set-1',
  COUNTRY_SET_2 = 'country-set-2',
  CRYPTO_SET_1 = 'crypto-set-1',
  CRYPTO_SET_2 = 'crypto-set-2',
  CRYPTO_SET_3 = 'crypto-set-3',
  EDITOR = 'editor',
  EDUCATION = 'education',
  FILES = 'files',
  FINANCE_AND_ECOMMERCE = 'finance-and-ecommerce',
  GENERAL = 'general',
  LAYOUT = 'layout',
  SECURITY = 'security',
  TIME = 'time',
  USERS = 'users',
  COUNTRY_FLAGS = 'country-flags',
  FIAT_CURRENCIES = 'fiat-currencies',
  WEATHER = 'weather',
}
