'use client';

import type { Icon } from '@phosphor-icons/react';
import {
  CameraIcon,
  FolderIcon,
  FolderOpenIcon,
  DatabaseIcon,
  FileArchiveIcon,
  FileAudioIcon,
  FileCIcon,
  FileCSharpIcon,
  FileCodeIcon,
  FileCppIcon,
  FileCssIcon,
  FileDocIcon,
  FileHtmlIcon,
  FileIcon as FileDefaultIcon,
  FileIniIcon,
  FileJsIcon,
  FileJsxIcon,
  FileMdIcon,
  FilePdfIcon,
  FilePptIcon,
  FilePyIcon,
  FileRsIcon,
  FileSqlIcon,
  FileTsIcon,
  FileTsxIcon,
  FileTxtIcon,
  FileVueIcon,
  TableIcon,
  TerminalIcon,
  VideoCameraIcon,
} from '@phosphor-icons/react';

/**
 * Mapping from file extension to Phosphor icon component.
 * Extensions not listed here fall back to DEFAULT_FILE_ICON.
 */
export const FILE_EXTENSION_ICON_MAP: Record<string, Icon> = {
  // Documents
  pdf: FilePdfIcon,
  doc: FileDocIcon,
  docx: FileDocIcon,
  odt: FileDocIcon,
  rtf: FileDocIcon,
  xls: TableIcon,
  xlsx: TableIcon,
  ods: TableIcon,
  ppt: FilePptIcon,
  pptx: FilePptIcon,
  odp: FilePptIcon,
  txt: FileTxtIcon,
  text: FileTxtIcon,
  csv: TableIcon,
  tsv: TableIcon,
  tab: TableIcon,

  // Code - Web
  html: FileHtmlIcon,
  htm: FileHtmlIcon,
  xhtml: FileHtmlIcon,
  shtml: FileHtmlIcon,
  css: FileCssIcon,
  scss: FileCssIcon,
  sass: FileCssIcon,
  less: FileCssIcon,
  styl: FileCssIcon,
  stylus: FileCssIcon,
  postcss: FileCssIcon,
  js: FileJsIcon,
  mjs: FileJsIcon,
  cjs: FileJsIcon,
  coffee: FileJsIcon,
  litcoffee: FileJsIcon,
  jsx: FileJsxIcon,
  ts: FileTsIcon,
  mts: FileTsIcon,
  cts: FileTsIcon,
  tsx: FileTsxIcon,
  vue: FileVueIcon,
  svelte: FileCodeIcon,
  astro: FileCodeIcon,

  // Code - Backend
  py: FilePyIcon,
  pyw: FilePyIcon,
  pyi: FilePyIcon,
  pyx: FilePyIcon,
  c: FileCIcon,
  h: FileCIcon,
  cpp: FileCppIcon,
  cc: FileCppIcon,
  cxx: FileCppIcon,
  hpp: FileCppIcon,
  hh: FileCppIcon,
  hxx: FileCppIcon,
  ino: FileCppIcon,
  cs: FileCSharpIcon,
  csx: FileCSharpIcon,
  rs: FileRsIcon,
  rb: FileCodeIcon,
  erb: FileCodeIcon,
  php: FileCodeIcon,
  java: FileCodeIcon,
  kt: FileCodeIcon,
  kts: FileCodeIcon,
  swift: FileCodeIcon,
  go: FileCodeIcon,
  r: FileCodeIcon,
  scala: FileCodeIcon,
  groovy: FileCodeIcon,
  dart: FileCodeIcon,
  ex: FileCodeIcon,
  exs: FileCodeIcon,
  lua: FileCodeIcon,
  hs: FileCodeIcon,
  erl: FileCodeIcon,
  ml: FileCodeIcon,
  nim: FileCodeIcon,
  zig: FileCodeIcon,
  cr: FileCodeIcon,
  d: FileCodeIcon,
  jl: FileCodeIcon,
  clj: FileCodeIcon,
  cljs: FileCodeIcon,
  sol: FileCodeIcon,
  v: FileCodeIcon,
  vhd: FileCodeIcon,
  vhdl: FileCodeIcon,
  asm: FileCodeIcon,
  s: FileCodeIcon,
  pl: FileCodeIcon,
  pm: FileCodeIcon,
  pas: FileCodeIcon,
  f90: FileCodeIcon,
  cob: FileCodeIcon,
  lisp: FileCodeIcon,
  el: FileCodeIcon,
  rkt: FileCodeIcon,
  tcl: FileCodeIcon,
  vb: FileCodeIcon,
  vbs: FileCodeIcon,
  ada: FileCodeIcon,

  // Config & Data
  json: FileIniIcon,
  jsonc: FileIniIcon,
  json5: FileIniIcon,
  jsonl: FileIniIcon,
  ndjson: FileIniIcon,
  geojson: FileIniIcon,
  yaml: FileIniIcon,
  yml: FileIniIcon,
  xml: FileIniIcon,
  xsd: FileIniIcon,
  xsl: FileIniIcon,
  xslt: FileIniIcon,
  dtd: FileIniIcon,
  toml: FileIniIcon,
  ini: FileIniIcon,
  cfg: FileIniIcon,
  conf: FileIniIcon,
  config: FileIniIcon,
  properties: FileIniIcon,
  env: FileIniIcon,
  dotenv: FileIniIcon,
  plist: FileIniIcon,

  // Shell & Scripts
  sh: TerminalIcon,
  bash: TerminalIcon,
  zsh: TerminalIcon,
  fish: TerminalIcon,
  ksh: TerminalIcon,
  csh: TerminalIcon,
  tcsh: TerminalIcon,
  ash: TerminalIcon,
  dash: TerminalIcon,
  ps1: TerminalIcon,
  psm1: TerminalIcon,
  psd1: TerminalIcon,
  bat: TerminalIcon,
  cmd: TerminalIcon,
  btm: TerminalIcon,

  // Database & Query
  sql: FileSqlIcon,
  ddl: FileSqlIcon,
  dml: FileSqlIcon,
  mysql: FileSqlIcon,
  pgsql: FileSqlIcon,
  plsql: FileSqlIcon,
  plpgsql: FileSqlIcon,
  graphql: DatabaseIcon,
  gql: DatabaseIcon,
  prisma: DatabaseIcon,
  cql: DatabaseIcon,
  hql: DatabaseIcon,
  cypher: DatabaseIcon,
  sparql: DatabaseIcon,
  rq: DatabaseIcon,
  redis: DatabaseIcon,

  // Markdown & Docs
  md: FileMdIcon,
  mdx: FileMdIcon,
  markdown: FileMdIcon,
  mdown: FileMdIcon,
  mkd: FileMdIcon,
  mkdn: FileMdIcon,
  rst: FileDocIcon,
  tex: FileDocIcon,
  latex: FileDocIcon,

  // Images
  png: CameraIcon,
  jpg: CameraIcon,
  jpeg: CameraIcon,
  gif: CameraIcon,
  webp: CameraIcon,
  bmp: CameraIcon,
  ico: CameraIcon,
  svg: CameraIcon,
  psd: CameraIcon,
  ai: CameraIcon,
  eps: CameraIcon,
  fig: CameraIcon,
  sketch: CameraIcon,
  xd: CameraIcon,

  // Video
  mp4: VideoCameraIcon,
  mov: VideoCameraIcon,
  avi: VideoCameraIcon,
  mkv: VideoCameraIcon,
  webm: VideoCameraIcon,
  wmv: VideoCameraIcon,
  flv: VideoCameraIcon,
  m4v: VideoCameraIcon,

  // Audio
  mp3: FileAudioIcon,
  wav: FileAudioIcon,
  flac: FileAudioIcon,
  aac: FileAudioIcon,
  m4a: FileAudioIcon,
  ogg: FileAudioIcon,
  wma: FileAudioIcon,
  aiff: FileAudioIcon,
  mid: FileAudioIcon,
  midi: FileAudioIcon,

  // Archives
  zip: FileArchiveIcon,
  rar: FileArchiveIcon,
  '7z': FileArchiveIcon,
  tar: FileArchiveIcon,
  gz: FileArchiveIcon,
  bz2: FileArchiveIcon,
  xz: FileArchiveIcon,

  // Special/System
  dockerfile: FileCodeIcon,
  lock: FileIniIcon,
  log: FileTxtIcon,
  gitignore: FileIniIcon,
  license: FileDocIcon,
};

export const DEFAULT_FILE_ICON: Icon = FileDefaultIcon;

export { FolderIcon as FolderClosedIcon, FolderOpenIcon as FolderOpenedIcon };
