/**
 * Values for `KeyboardEvent.key` / `KeyboardEvent.code` used across the platform.
 * Prefer `event.key` for Enter, arrows, Escape; many letter entries match `event.code` (e.g. KeyA).
 */
export const KEYBOARD_KEYS = {
  A: 'KeyA',
  B: 'KeyB',
  C: 'KeyC',
  D: 'KeyD',
  E: 'KeyE',
  F: 'KeyF',
  G: 'KeyG',
  H: 'KeyH',
  I: 'KeyI',
  J: 'KeyJ',
  K: 'KeyK',
  L: 'KeyL',
  M: 'KeyM',
  N: 'KeyN',
  O: 'KeyO',
  P: 'KeyP',
  Q: 'KeyQ',
  R: 'KeyR',
  S: 'KeyS',
  T: 'KeyT',
  U: 'KeyU',
  V: 'KeyV',
  W: 'KeyW',
  X: 'KeyX',
  Y: 'KeyY',
  Z: 'KeyZ',
  ENTER: 'Enter',
  ESCAPE: 'Escape',
  SPACE: 'Space',
  ARROW_UP: 'ArrowUp',
  ARROW_DOWN: 'ArrowDown',
  ARROW_LEFT: 'ArrowLeft',
  ARROW_RIGHT: 'ArrowRight',
  BACKSPACE: 'Backspace',
  DELETE: 'Delete',
  SLASH: 'Slash',
  DOT: 'Period',
  COMMA: 'Comma',
  SHIFT: 'Shift',
  META: 'Meta',
  CONTROL: 'Control',
  TAB: 'Tab',
} as const;
