import { Copy, Download, ExternalLink, Link, Pencil, Scissors, Share, Trash2 } from 'lucide-react';
import {
  type ContextMenuAction,
  FILE_TYPE,
  type FileItem,
  type SortOption,
} from 'modules/pace/components/files/file-tree.types';

export const DATE_FORMAT = "EEEE, d MMMM yyyy 'at' h:mm a";

export const SORT_OPTIONS: { value: SortOption; label: string }[] = [
  { value: 'date_modified', label: 'Date modified' },
  { value: 'name', label: 'Name' },
  { value: 'size', label: 'Size' },
  { value: 'type', label: 'Type' },
];

export const CONTEXT_MENU_ACTIONS: ContextMenuAction[] = [
  { id: 'open-in-tab', label: 'Open in Tab', icon: ExternalLink, fileOnly: true },
  { id: 'work-with-zamp', label: 'Work with Zamp', icon: Link },
  { id: 'rename', label: 'Rename', icon: Pencil },
  { id: 'duplicate', label: 'Duplicate', icon: Copy },
  { id: 'copy', label: 'Copy', icon: Copy },
  { id: 'cut', label: 'Cut', icon: Scissors },
  { id: 'share', label: 'Share', icon: Share },
  { id: 'download', label: 'Download', icon: Download },
  { id: 'delete', label: 'Delete', icon: Trash2, isDestructive: true },
];

export const FILE_TYPE_LABELS: Record<string, string> = {
  // Documents
  PDF: 'PDF file',
  DOC: 'Word document',
  DOCX: 'Word document',
  XLS: 'Excel spreadsheet',
  XLSX: 'Excel spreadsheet',
  PPT: 'PowerPoint presentation',
  PPTX: 'PowerPoint presentation',
  ODT: 'OpenDocument text',
  ODS: 'OpenDocument spreadsheet',
  ODP: 'OpenDocument presentation',
  RTF: 'Rich text file',
  TXT: 'Text file',
  CSV: 'CSV file',

  // Code - Web
  HTML: 'HTML file',
  HTM: 'HTML file',
  CSS: 'CSS file',
  SCSS: 'SCSS file',
  SASS: 'Sass file',
  LESS: 'Less file',
  JS: 'JavaScript file',
  JSX: 'JSX file',
  TS: 'TypeScript file',
  TSX: 'TSX file',
  VUE: 'Vue file',
  SVELTE: 'Svelte file',

  // Code - Backend
  PY: 'Python file',
  RB: 'Ruby file',
  PHP: 'PHP file',
  JAVA: 'Java file',
  KT: 'Kotlin file',
  SWIFT: 'Swift file',
  GO: 'Go file',
  RS: 'Rust file',
  C: 'C file',
  CPP: 'C++ file',
  CS: 'C# file',
  R: 'R file',
  SCALA: 'Scala file',

  // Code - Config
  JSON: 'JSON file',
  YAML: 'YAML file',
  YML: 'YAML file',
  XML: 'XML file',
  TOML: 'TOML file',
  INI: 'INI file',
  ENV: 'Environment file',

  // Code - Shell
  SH: 'Shell script',
  BASH: 'Bash script',
  ZSH: 'Zsh script',
  PS1: 'PowerShell script',
  BAT: 'Batch file',

  // Code - Database
  SQL: 'SQL file',
  GRAPHQL: 'GraphQL file',
  PRISMA: 'Prisma file',

  // Markdown & Docs
  MD: 'Markdown file',
  MDX: 'MDX file',
  RST: 'reStructuredText file',
  TEX: 'LaTeX file',

  // Images
  PNG: 'PNG image',
  JPG: 'JPEG image',
  JPEG: 'JPEG image',
  GIF: 'GIF image',
  WEBP: 'WebP image',
  BMP: 'Bitmap image',
  ICO: 'Icon file',
  SVG: 'SVG image',
  PSD: 'Photoshop file',
  AI: 'Illustrator file',
  EPS: 'EPS file',
  FIG: 'Figma file',
  SKETCH: 'Sketch file',
  XD: 'Adobe XD file',

  // Video
  MP4: 'MP4 video',
  MOV: 'QuickTime video',
  AVI: 'AVI video',
  MKV: 'MKV video',
  WEBM: 'WebM video',
  WMV: 'WMV video',
  FLV: 'Flash video',
  M4V: 'M4V video',

  // Audio
  MP3: 'MP3 audio',
  WAV: 'WAV audio',
  FLAC: 'FLAC audio',
  AAC: 'AAC audio',
  M4A: 'M4A audio',
  OGG: 'OGG audio',
  WMA: 'WMA audio',
  AIFF: 'AIFF audio',
  MID: 'MIDI file',
  MIDI: 'MIDI file',

  // Archives
  ZIP: 'ZIP archive',
  RAR: 'RAR archive',
  '7Z': '7-Zip archive',
  TAR: 'TAR archive',
  GZ: 'Gzip archive',
  BZ2: 'Bzip2 archive',
  XZ: 'XZ archive',

  // Fonts
  TTF: 'TrueType font',
  OTF: 'OpenType font',
  WOFF: 'Web font',
  WOFF2: 'Web font',
  EOT: 'Embedded font',

  // Executables
  EXE: 'Windows executable',
  MSI: 'Windows installer',
  DMG: 'macOS disk image',
  APP: 'macOS application',
  DEB: 'Debian package',
  RPM: 'RPM package',
  APK: 'Android package',
  IPA: 'iOS application',

  // 3D & CAD
  OBJ: '3D object file',
  FBX: 'FBX file',
  STL: 'STL file',
  GLTF: 'glTF file',
  GLB: 'GLB file',
  BLEND: 'Blender file',
  DWG: 'AutoCAD file',

  // Ebooks
  EPUB: 'EPUB ebook',
  MOBI: 'Kindle ebook',
  AZW: 'Kindle ebook',

  // Special/System
  GITIGNORE: 'Git ignore file',
  DOCKERFILE: 'Dockerfile',
  LOCK: 'Lock file',
  LOG: 'Log file',
  LICENSE: 'License file',
};

export const MOCK_FILES: FileItem[] = [
  {
    path: 'Budget spreadsheet',
    name: 'Budget spreadsheet',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771349214794,
  },
  {
    path: 'Budget spreadsheet/first_dance_song.mp3',
    name: 'first_dance_song.mp3',
    type: FILE_TYPE.FILE,
    size: 4500000,
    mtime_ms: 1771354001854,
  },
  {
    path: 'Budget spreadsheet/venue_options.md',
    name: 'venue_options.md',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354001843,
  },
  {
    path: 'Budget spreadsheet/guest_addresses.xlsx',
    name: 'guest_addresses.xlsx',
    type: FILE_TYPE.FILE,
    size: 15360,
    mtime_ms: 1771354001865,
  },
  {
    path: 'Budget spreadsheet/vendor_contacts.docx',
    name: 'vendor_contacts.docx',
    type: FILE_TYPE.FILE,
    size: 8192,
    mtime_ms: 1770790929081,
  },
  {
    path: 'Budget spreadsheet/rsvp_form.css',
    name: 'rsvp_form.css',
    type: FILE_TYPE.FILE,
    size: 1024,
    mtime_ms: 1770816275272,
  },
  {
    path: 'Budget spreadsheet/rsvp_form.html',
    name: 'rsvp_form.html',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1770816275770,
  },
  {
    path: 'Budget spreadsheet/Guest list',
    name: 'Guest list',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1770816275290,
  },
  {
    path: 'Budget spreadsheet/Guest list/ceremony_songs.zip',
    name: 'ceremony_songs.zip',
    type: FILE_TYPE.FILE,
    size: 52428800,
    mtime_ms: 1770986876296,
  },
  {
    path: 'Budget spreadsheet/Guest list/Flowers',
    name: 'Flowers',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1770986877373,
  },
  {
    path: 'Budget spreadsheet/Guest list/Flowers/dress_inspiration.mp4',
    name: 'dress_inspiration.mp4',
    type: FILE_TYPE.FILE,
    size: 104857600,
    mtime_ms: 1770986876590,
  },
  {
    path: 'Budget spreadsheet/Guest list/Flowers/bouquet_design.psd',
    name: 'bouquet_design.psd',
    type: FILE_TYPE.FILE,
    size: 25600000,
    mtime_ms: 1770986877100,
  },
  {
    path: 'Budget spreadsheet/Guest list/Flowers/flower_arrangement.png',
    name: 'flower_arrangement.png',
    type: FILE_TYPE.FILE,
    size: 2048000,
    mtime_ms: 1770986877200,
  },
  {
    path: 'Budget spreadsheet/seating_chart.pdf',
    name: 'seating_chart.pdf',
    type: FILE_TYPE.FILE,
    size: 512000,
    mtime_ms: 1771354002000,
  },
  {
    path: 'Budget spreadsheet/wedding_timeline.json',
    name: 'wedding_timeline.json',
    type: FILE_TYPE.FILE,
    size: 4096,
    mtime_ms: 1771354002100,
  },
  {
    path: 'Budget spreadsheet/invitation_template.svg',
    name: 'invitation_template.svg',
    type: FILE_TYPE.FILE,
    size: 8192,
    mtime_ms: 1771354002200,
  },
  {
    path: 'Budget spreadsheet/Scripts',
    name: 'Scripts',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354002300,
  },
  {
    path: 'Budget spreadsheet/Scripts/rsvp_handler.py',
    name: 'rsvp_handler.py',
    type: FILE_TYPE.FILE,
    size: 3072,
    mtime_ms: 1771354002400,
  },
  {
    path: 'Budget spreadsheet/Scripts/email_sender.ts',
    name: 'email_sender.ts',
    type: FILE_TYPE.FILE,
    size: 2560,
    mtime_ms: 1771354002500,
  },
  {
    path: 'Budget spreadsheet/Scripts/database_backup.sql',
    name: 'database_backup.sql',
    type: FILE_TYPE.FILE,
    size: 102400,
    mtime_ms: 1771354002600,
  },
  {
    path: 'Budget spreadsheet/config.yaml',
    name: 'config.yaml',
    type: FILE_TYPE.FILE,
    size: 1536,
    mtime_ms: 1771354002700,
  },
  {
    path: 'Budget spreadsheet/ceremony_photos.rar',
    name: 'ceremony_photos.rar',
    type: FILE_TYPE.FILE,
    size: 157286400,
    mtime_ms: 1771354002800,
  },
  {
    path: 'Budget spreadsheet/speech_notes.txt',
    name: 'speech_notes.txt',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354002900,
  },
  {
    path: 'Budget spreadsheet/wedding_logo.ai',
    name: 'wedding_logo.ai',
    type: FILE_TYPE.FILE,
    size: 5120000,
    mtime_ms: 1771354003000,
  },
  {
    path: 'Budget spreadsheet/background_music.wav',
    name: 'background_music.wav',
    type: FILE_TYPE.FILE,
    size: 45000000,
    mtime_ms: 1771354003100,
  },
  {
    path: 'Budget spreadsheet/venue_3d_model.gltf',
    name: 'venue_3d_model.gltf',
    type: FILE_TYPE.FILE,
    size: 8500000,
    mtime_ms: 1771354003200,
  },
  // Deeply nested project structure
  {
    path: 'Project Alpha',
    name: 'Project Alpha',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354010000,
  },
  {
    path: 'Project Alpha/README.md',
    name: 'README.md',
    type: FILE_TYPE.FILE,
    size: 4096,
    mtime_ms: 1771354010100,
  },
  {
    path: 'Project Alpha/package.json',
    name: 'package.json',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354010200,
  },
  {
    path: 'Project Alpha/src',
    name: 'src',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354011000,
  },
  {
    path: 'Project Alpha/src/index.ts',
    name: 'index.ts',
    type: FILE_TYPE.FILE,
    size: 512,
    mtime_ms: 1771354011100,
  },
  {
    path: 'Project Alpha/src/app.tsx',
    name: 'app.tsx',
    type: FILE_TYPE.FILE,
    size: 3072,
    mtime_ms: 1771354011200,
  },
  {
    path: 'Project Alpha/src/components',
    name: 'components',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354012000,
  },
  {
    path: 'Project Alpha/src/components/Button.tsx',
    name: 'Button.tsx',
    type: FILE_TYPE.FILE,
    size: 1536,
    mtime_ms: 1771354012100,
  },
  {
    path: 'Project Alpha/src/components/Input.tsx',
    name: 'Input.tsx',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354012200,
  },
  {
    path: 'Project Alpha/src/components/Modal.tsx',
    name: 'Modal.tsx',
    type: FILE_TYPE.FILE,
    size: 3584,
    mtime_ms: 1771354012300,
  },
  {
    path: 'Project Alpha/src/components/ui',
    name: 'ui',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354013000,
  },
  {
    path: 'Project Alpha/src/components/ui/Card.tsx',
    name: 'Card.tsx',
    type: FILE_TYPE.FILE,
    size: 1024,
    mtime_ms: 1771354013100,
  },
  {
    path: 'Project Alpha/src/components/ui/Badge.tsx',
    name: 'Badge.tsx',
    type: FILE_TYPE.FILE,
    size: 768,
    mtime_ms: 1771354013200,
  },
  {
    path: 'Project Alpha/src/components/ui/icons',
    name: 'icons',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354014000,
  },
  {
    path: 'Project Alpha/src/components/ui/icons/ArrowIcon.tsx',
    name: 'ArrowIcon.tsx',
    type: FILE_TYPE.FILE,
    size: 512,
    mtime_ms: 1771354014100,
  },
  {
    path: 'Project Alpha/src/components/ui/icons/CheckIcon.tsx',
    name: 'CheckIcon.tsx',
    type: FILE_TYPE.FILE,
    size: 512,
    mtime_ms: 1771354014200,
  },
  {
    path: 'Project Alpha/src/components/ui/icons/CloseIcon.tsx',
    name: 'CloseIcon.tsx',
    type: FILE_TYPE.FILE,
    size: 512,
    mtime_ms: 1771354014300,
  },
  {
    path: 'Project Alpha/src/hooks',
    name: 'hooks',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354015000,
  },
  {
    path: 'Project Alpha/src/hooks/useAuth.ts',
    name: 'useAuth.ts',
    type: FILE_TYPE.FILE,
    size: 2560,
    mtime_ms: 1771354015100,
  },
  {
    path: 'Project Alpha/src/hooks/useDebounce.ts',
    name: 'useDebounce.ts',
    type: FILE_TYPE.FILE,
    size: 1024,
    mtime_ms: 1771354015200,
  },
  {
    path: 'Project Alpha/src/utils',
    name: 'utils',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354016000,
  },
  {
    path: 'Project Alpha/src/utils/helpers.ts',
    name: 'helpers.ts',
    type: FILE_TYPE.FILE,
    size: 4096,
    mtime_ms: 1771354016100,
  },
  {
    path: 'Project Alpha/src/utils/constants.ts',
    name: 'constants.ts',
    type: FILE_TYPE.FILE,
    size: 1536,
    mtime_ms: 1771354016200,
  },
  {
    path: 'Project Alpha/src/utils/api',
    name: 'api',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354017000,
  },
  {
    path: 'Project Alpha/src/utils/api/client.ts',
    name: 'client.ts',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354017100,
  },
  {
    path: 'Project Alpha/src/utils/api/endpoints.ts',
    name: 'endpoints.ts',
    type: FILE_TYPE.FILE,
    size: 3072,
    mtime_ms: 1771354017200,
  },
  {
    path: 'Project Alpha/src/utils/api/types.ts',
    name: 'types.ts',
    type: FILE_TYPE.FILE,
    size: 1536,
    mtime_ms: 1771354017300,
  },
  {
    path: 'Project Alpha/src/styles',
    name: 'styles',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354018000,
  },
  {
    path: 'Project Alpha/src/styles/globals.css',
    name: 'globals.css',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354018100,
  },
  {
    path: 'Project Alpha/src/styles/variables.scss',
    name: 'variables.scss',
    type: FILE_TYPE.FILE,
    size: 1024,
    mtime_ms: 1771354018200,
  },
  {
    path: 'Project Alpha/tests',
    name: 'tests',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354019000,
  },
  {
    path: 'Project Alpha/tests/setup.ts',
    name: 'setup.ts',
    type: FILE_TYPE.FILE,
    size: 512,
    mtime_ms: 1771354019100,
  },
  {
    path: 'Project Alpha/tests/unit',
    name: 'unit',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354020000,
  },
  {
    path: 'Project Alpha/tests/unit/Button.test.tsx',
    name: 'Button.test.tsx',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354020100,
  },
  {
    path: 'Project Alpha/tests/unit/helpers.test.ts',
    name: 'helpers.test.ts',
    type: FILE_TYPE.FILE,
    size: 3072,
    mtime_ms: 1771354020200,
  },
  {
    path: 'Project Alpha/tests/e2e',
    name: 'e2e',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354021000,
  },
  {
    path: 'Project Alpha/tests/e2e/auth.spec.ts',
    name: 'auth.spec.ts',
    type: FILE_TYPE.FILE,
    size: 4096,
    mtime_ms: 1771354021100,
  },
  {
    path: 'Project Alpha/tests/e2e/dashboard.spec.ts',
    name: 'dashboard.spec.ts',
    type: FILE_TYPE.FILE,
    size: 5120,
    mtime_ms: 1771354021200,
  },
  {
    path: 'Project Alpha/config',
    name: 'config',
    type: FILE_TYPE.DIRECTORY,
    size: null,
    mtime_ms: 1771354022000,
  },
  {
    path: 'Project Alpha/config/tsconfig.json',
    name: 'tsconfig.json',
    type: FILE_TYPE.FILE,
    size: 1024,
    mtime_ms: 1771354022100,
  },
  {
    path: 'Project Alpha/config/eslint.config.js',
    name: 'eslint.config.js',
    type: FILE_TYPE.FILE,
    size: 2048,
    mtime_ms: 1771354022200,
  },
  {
    path: 'Project Alpha/config/vite.config.ts',
    name: 'vite.config.ts',
    type: FILE_TYPE.FILE,
    size: 1536,
    mtime_ms: 1771354022300,
  },
];
