import {
  Clipboard,
  Copy,
  Download,
  ExternalLink,
  FilePlus,
  FolderPlus,
  FolderUp,
  MessageSquare,
  Pencil,
  Scissors,
  Trash2,
  Upload,
} from 'lucide-react';
import { type ContextMenuAction, type SortOption } from '@/modules/pace/components/files/file-tree.types';

export const DATE_FORMAT = "EEEE, d MMMM yyyy 'at' h:mm a";

export const DIRECT_UPLOAD_THRESHOLD_BYTES = 1 * 1024 * 1024; // 1MB
export const DEFAULT_CHUNK_SIZE = 6 * 1024 * 1024; // 6MB chunk size
export const PARALLEL_CHUNK_CONCURRENCY = 6; // Upload 6 chunks in parallel
export const MAX_CHUNK_RETRIES = 3; // Retry failed chunks up to 3 times
export const MAX_FOLDER_UPLOAD_FILES = 200;

export const FILE_TOAST_MESSAGES = {
  CANNOT_RENAME_PROTECTED: 'Cannot rename protected folders',
  CANNOT_DELETE_PROTECTED: 'Cannot delete protected folders',
  CANNOT_CUT_PROTECTED: 'Cannot cut protected folders',
  CANNOT_PASTE_INTO_ITSELF: 'Cannot paste a folder into itself',
  CANNOT_MOVE_PROTECTED: 'Cannot move protected folders',
  CANNOT_MOVE_PROTECTED_INTO_EACH_OTHER: 'Cannot move protected folders into each other',
  FAILED_TO_CREATE_ITEM: 'Failed to create item',
  FAILED_TO_RENAME: 'Failed to rename',
  FAILED_TO_MOVE_COPY: 'Failed to move/copy',
  FAILED_TO_RESOLVE_CONFLICT: 'Failed to resolve conflict',
  FAILED_TO_SAVE_FILE: 'Failed to save file',
  FAILED_TO_DELETE_FILE: 'Failed to delete file',
  FAILED_TO_DELETE_ITEM: 'Failed to delete item',
  FILE_DELETED: 'File deleted',
  FOLDER_DELETED: 'Folder deleted',
  FILE_MODIFIED_EXTERNALLY: 'File was modified externally',
  FILE_CONFLICT_DESCRIPTION: 'This file was changed while you were editing. Choose an action:',
  FORCE_SAVE: 'Force Save',
  RELOAD_FILE: 'Reload File',
} as const;

export const CONTEXT_MENU_ACTION_IDS = {
  CREATE_FILE: 'create-file',
  CREATE_FOLDER: 'create-folder',
  UPLOAD_FILE: 'upload-file',
  UPLOAD_FOLDER: 'upload-folder',
  OPEN_IN_TAB: 'open-in-tab',
  REFERENCE_IN_CHAT: 'reference-in-chat',
  DOWNLOAD: 'download',
  RENAME: 'rename',
  DUPLICATE: 'duplicate',
  COPY: 'copy',
  CUT: 'cut',
  PASTE: 'paste',
  DELETE: 'delete',
} as const;

export const FILE_VIEWER_HEADER_ACTION_IDS = {
  DOWNLOAD: 'download',
  DELETE: 'delete',
} as const;

export const SAVE_STATUS = {
  IDLE: 'idle',
  SAVING: 'saving',
  SAVED: 'saved',
} as const;

export type SaveStatus = (typeof SAVE_STATUS)[keyof typeof SAVE_STATUS];

export type FileViewerHeaderActionId =
  (typeof FILE_VIEWER_HEADER_ACTION_IDS)[keyof typeof FILE_VIEWER_HEADER_ACTION_IDS];

export const SORT_OPTIONS: { value: SortOption; label: string }[] = [
  { value: 'date_modified', label: 'Date modified' },
  { value: 'name', label: 'Name' },
  { value: 'size', label: 'Size' },
  { value: 'type', label: 'Type' },
];

export const CONTEXT_MENU_ACTIONS: ContextMenuAction[] = [
  { id: CONTEXT_MENU_ACTION_IDS.CREATE_FILE, label: 'Create File', icon: FilePlus, folderOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.CREATE_FOLDER, label: 'Create Folder', icon: FolderPlus, folderOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.UPLOAD_FILE, label: 'Upload File', icon: Upload, folderOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.UPLOAD_FOLDER, label: 'Upload Folder', icon: FolderUp, folderOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.OPEN_IN_TAB, label: 'Open in Tab', icon: ExternalLink, fileOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.REFERENCE_IN_CHAT, label: 'Reference in Chat', icon: MessageSquare, fileOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.DOWNLOAD, label: 'Download', icon: Download },
  { id: CONTEXT_MENU_ACTION_IDS.RENAME, label: 'Rename', icon: Pencil },
  { id: CONTEXT_MENU_ACTION_IDS.DUPLICATE, label: 'Duplicate', icon: Copy },
  { id: CONTEXT_MENU_ACTION_IDS.COPY, label: 'Copy', icon: Copy },
  { id: CONTEXT_MENU_ACTION_IDS.CUT, label: 'Cut', icon: Scissors },
  { id: CONTEXT_MENU_ACTION_IDS.PASTE, label: 'Paste', icon: Clipboard, folderOnly: true },
  { id: CONTEXT_MENU_ACTION_IDS.DELETE, label: 'Delete', icon: Trash2, isDestructive: true },
];

export const FILE_VIEWER_HEADER_ACTIONS: ContextMenuAction[] = [
  { id: FILE_VIEWER_HEADER_ACTION_IDS.DOWNLOAD, label: 'Download', icon: Download },
  { id: FILE_VIEWER_HEADER_ACTION_IDS.DELETE, label: 'Delete', icon: Trash2, isDestructive: true },
];

// File categories for viewer selection
export const FILE_CATEGORY = {
  IMAGE: 'image',
  AUDIO: 'audio',
  VIDEO: 'video',
  PDF: 'pdf',
  MARKDOWN: 'markdown',
  HTML: 'html',
  CODE: 'code',
  UNKNOWN: 'unknown',
} as const;

export type FileCategory = (typeof FILE_CATEGORY)[keyof typeof FILE_CATEGORY];

export const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'ico'] as const;

export const AUDIO_EXTENSIONS = ['mp3', 'wav', 'flac', 'aac', 'm4a', 'ogg', 'wma', 'aiff'] as const;

export const VIDEO_EXTENSIONS = ['mp4', 'mov', 'avi', 'mkv', 'webm', 'wmv', 'flv', 'm4v'] as const;

export const PDF_EXTENSIONS = ['pdf'] as const;

export const MARKDOWN_EXTENSIONS = ['md', 'mdx'] as const;

export const HTML_EXTENSIONS = ['html', 'htm', 'xhtml', 'shtml'] as const;

export const EXTENSION_TO_MONACO_LANGUAGE: Record<string, string> = {
  // Web - JavaScript/TypeScript
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'typescript',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',

  // Web - Markup & Styles
  html: 'html',
  htm: 'html',
  xhtml: 'html',
  shtml: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  less: 'less',
  styl: 'stylus',
  stylus: 'stylus',
  postcss: 'css',

  // Backend - Common
  py: 'python',
  pyw: 'python',
  pyi: 'python',
  pyx: 'python',
  pxd: 'python',
  rb: 'ruby',
  erb: 'ruby',
  rake: 'ruby',
  gemspec: 'ruby',
  php: 'php',
  php3: 'php',
  php4: 'php',
  php5: 'php',
  php7: 'php',
  php8: 'php',
  phtml: 'php',
  phps: 'php',
  java: 'java',
  jsp: 'java',
  jspx: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  go: 'go',
  mod: 'go',
  rs: 'rust',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  hxx: 'cpp',
  ino: 'cpp',
  cs: 'csharp',
  csx: 'csharp',
  r: 'r',
  rmd: 'r',
  scala: 'scala',
  sc: 'scala',
  sbt: 'scala',
  groovy: 'groovy',
  gradle: 'groovy',
  gvy: 'groovy',
  gy: 'groovy',
  gsh: 'groovy',

  // Backend - Additional Languages
  dart: 'dart',
  ex: 'elixir',
  exs: 'elixir',
  eex: 'elixir',
  heex: 'elixir',
  leex: 'elixir',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  fsscript: 'fsharp',
  jl: 'julia',
  lua: 'lua',
  m: 'objective-c',
  mm: 'objective-c',
  pas: 'pascal',
  pp: 'pascal',
  inc: 'pascal',
  lpr: 'pascal',
  dpr: 'pascal',
  pl: 'perl',
  pm: 'perl',
  pod: 'perl',
  t: 'perl',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  coffee: 'coffeescript',
  litcoffee: 'coffeescript',
  scm: 'scheme',
  ss: 'scheme',
  rkt: 'scheme',
  tcl: 'tcl',
  tk: 'tcl',
  vb: 'vb',
  vbs: 'vb',
  bas: 'vb',
  frm: 'vb',
  cls: 'vb',
  sol: 'solidity',
  vy: 'solidity',
  qs: 'qsharp',
  v: 'systemverilog',
  sv: 'systemverilog',
  svh: 'systemverilog',
  vhd: 'vhdl',
  vhdl: 'vhdl',
  asm: 'asm',
  s: 'asm',
  hs: 'haskell',
  lhs: 'haskell',
  erl: 'erlang',
  hrl: 'erlang',
  ml: 'ocaml',
  mli: 'ocaml',
  nim: 'nim',
  nims: 'nim',
  nimble: 'nim',
  zig: 'zig',
  cr: 'crystal',
  d: 'd',
  di: 'd',
  ada: 'ada',
  adb: 'ada',
  ads: 'ada',
  f: 'fortran',
  f90: 'fortran',
  f95: 'fortran',
  f03: 'fortran',
  f08: 'fortran',
  for: 'fortran',
  fpp: 'fortran',
  cob: 'cobol',
  cbl: 'cobol',
  cpy: 'cobol',
  lisp: 'lisp',
  lsp: 'lisp',
  cl: 'lisp',
  el: 'lisp',
  prolog: 'prolog',
  pro: 'prolog',
  p: 'prolog',

  // Config & Data
  json: 'json',
  jsonc: 'jsonc',
  json5: 'json5',
  jsonl: 'json',
  ndjson: 'json',
  geojson: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  xml: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  xslt: 'xml',
  dtd: 'xml',
  rss: 'xml',
  atom: 'xml',
  svg: 'xml',
  plist: 'xml',
  toml: 'toml',
  ini: 'ini',
  cfg: 'ini',
  conf: 'ini',
  config: 'ini',
  properties: 'ini',
  env: 'plaintext',
  dotenv: 'plaintext',

  // Infrastructure/DevOps
  tf: 'hcl',
  tfvars: 'hcl',
  hcl: 'hcl',
  nomad: 'hcl',
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',
  bicep: 'bicep',
  azcli: 'azcli',
  vagrantfile: 'ruby',
  jenkinsfile: 'groovy',
  helmfile: 'yaml',

  // Shell & Scripts
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ksh: 'shell',
  csh: 'shell',
  tcsh: 'shell',
  ash: 'shell',
  dash: 'shell',
  ps1: 'powershell',
  psm1: 'powershell',
  psd1: 'powershell',
  ps1xml: 'powershell',
  bat: 'bat',
  cmd: 'bat',
  btm: 'bat',

  // Database
  sql: 'sql',
  ddl: 'sql',
  dml: 'sql',
  mysql: 'mysql',
  pgsql: 'pgsql',
  plsql: 'plsql',
  plpgsql: 'pgsql',
  redis: 'redis',
  cql: 'sql',
  hql: 'sql',
  graphql: 'graphql',
  gql: 'graphql',
  prisma: 'prisma',
  cypher: 'cypher',
  sparql: 'sparql',
  rq: 'sparql',

  // Template/Markup
  pug: 'pug',
  jade: 'pug',
  twig: 'twig',
  hbs: 'handlebars',
  handlebars: 'handlebars',
  mustache: 'handlebars',
  liquid: 'liquid',
  ejs: 'html',
  njk: 'html',
  nunjucks: 'html',
  jinja: 'jinja',
  jinja2: 'jinja',
  j2: 'jinja',
  rst: 'restructuredtext',
  rest: 'restructuredtext',
  proto: 'protobuf',
  proto3: 'protobuf',
  freemarker: 'freemarker',
  ftl: 'freemarker',
  razor: 'razor',
  cshtml: 'razor',
  vbhtml: 'razor',
  slim: 'slim',
  haml: 'haml',

  // Markdown & Docs
  md: 'markdown',
  mdx: 'markdown',
  markdown: 'markdown',
  mdown: 'markdown',
  mkd: 'markdown',
  mkdn: 'markdown',
  txt: 'plaintext',
  text: 'plaintext',
  csv: 'plaintext',
  tsv: 'plaintext',
  tab: 'plaintext',
  log: 'plaintext',
  out: 'plaintext',
  diff: 'diff',
  patch: 'diff',
  tex: 'latex',
  latex: 'latex',
  ltx: 'latex',
  sty: 'latex',
  bib: 'bibtex',
  bibtex: 'bibtex',
  org: 'plaintext',
  adoc: 'asciidoc',
  asciidoc: 'asciidoc',
  asc: 'asciidoc',

  // Other/Specialized
  apex: 'apex',
  trigger: 'apex',
  abap: 'abap',
  sb: 'sb',
  st: 'st',
  pq: 'powerquery',
  pqm: 'powerquery',
  wgsl: 'wgsl',
  typespec: 'typespec',
  tsp: 'typespec',
  glsl: 'glsl',
  vert: 'glsl',
  frag: 'glsl',
  geom: 'glsl',
  comp: 'glsl',
  hlsl: 'hlsl',
  fx: 'hlsl',
  fxh: 'hlsl',
  cg: 'cg',
  cu: 'cuda',
  cuh: 'cuda',
  cmake: 'cmake',
  make: 'makefile',
  makefile: 'makefile',
  mk: 'makefile',
  mak: 'makefile',
  gnumakefile: 'makefile',
  automake: 'makefile',
  am: 'makefile',

  // Special files (no extension but recognizable)
  gitignore: 'plaintext',
  gitattributes: 'plaintext',
  gitmodules: 'ini',
  editorconfig: 'ini',
  npmrc: 'ini',
  nvmrc: 'plaintext',
  babelrc: 'json',
  eslintrc: 'json',
  prettierrc: 'json',
  stylelintrc: 'json',
  browserslistrc: 'plaintext',
  htaccess: 'apache',
  htpasswd: 'plaintext',
  nginx: 'nginx',
  caddyfile: 'plaintext',
  procfile: 'plaintext',
  gemfile: 'ruby',
  rakefile: 'ruby',
  podfile: 'ruby',
  fastfile: 'ruby',
  appfile: 'ruby',
  brewfile: 'ruby',
  berksfile: 'ruby',
  guardfile: 'ruby',
  puppetfile: 'ruby',
  thorfile: 'ruby',
  capfile: 'ruby',
  jbuilder: 'ruby',
  rabl: 'ruby',
  podspec: 'ruby',
};

export const MONACO_EDITABLE_EXTENSIONS = [
  // Plain text & Markdown
  'txt',
  'text',
  'md',
  'mdx',
  'markdown',
  'mdown',
  'mkd',
  'mkdn',
  'rst',
  'rest',
  'org',
  'adoc',
  'asciidoc',
  'asc',

  // Web - JavaScript/TypeScript
  'js',
  'mjs',
  'cjs',
  'jsx',
  'ts',
  'mts',
  'cts',
  'tsx',
  'vue',
  'svelte',
  'astro',
  'coffee',
  'litcoffee',

  // Web - Markup & Styles
  'html',
  'htm',
  'xhtml',
  'shtml',
  'css',
  'scss',
  'sass',
  'less',
  'styl',
  'stylus',
  'postcss',
  'pug',
  'jade',

  // Backend - Common
  'py',
  'pyw',
  'pyi',
  'pyx',
  'pxd',
  'rb',
  'erb',
  'rake',
  'gemspec',
  'php',
  'php3',
  'php4',
  'php5',
  'php7',
  'php8',
  'phtml',
  'phps',
  'java',
  'jsp',
  'jspx',
  'kt',
  'kts',
  'swift',
  'go',
  'mod',
  'rs',
  'c',
  'h',
  'cpp',
  'cc',
  'cxx',
  'hpp',
  'hh',
  'hxx',
  'ino',
  'cs',
  'csx',
  'r',
  'rmd',
  'rnw',
  'snw',
  'rhtml',
  'scala',
  'sc',
  'sbt',
  'groovy',
  'gradle',
  'gvy',
  'gy',
  'gsh',

  // Backend - Additional Languages
  'dart',
  'ex',
  'exs',
  'eex',
  'heex',
  'leex',
  'fs',
  'fsi',
  'fsx',
  'fsscript',
  'jl',
  'lua',
  'm',
  'mm',
  'pas',
  'pp',
  'inc',
  'lpr',
  'dpr',
  'pl',
  'pm',
  'pod',
  't',
  'clj',
  'cljs',
  'cljc',
  'edn',
  'scm',
  'ss',
  'rkt',
  'tcl',
  'tk',
  'vb',
  'vbs',
  'bas',
  'frm',
  'sol',
  'vy',
  'qs',
  'v',
  'sv',
  'svh',
  'vhd',
  'vhdl',
  'asm',
  's',
  'hs',
  'lhs',
  'erl',
  'hrl',
  'ml',
  'mli',
  'nim',
  'nims',
  'nimble',
  'zig',
  'cr',
  'd',
  'di',
  'ada',
  'adb',
  'ads',
  'f',
  'f90',
  'f95',
  'f03',
  'f08',
  'for',
  'fpp',
  'cob',
  'cbl',
  'cpy',
  'lisp',
  'lsp',
  'cl',
  'el',
  'prolog',
  'pro',
  'p',

  // Config & Data
  'json',
  'jsonc',
  'json5',
  'jsonl',
  'ndjson',
  'geojson',
  'yaml',
  'yml',
  'xml',
  'xsd',
  'xsl',
  'xslt',
  'dtd',
  'rss',
  'atom',
  'plist',
  'toml',
  'ini',
  'cfg',
  'conf',
  'config',
  'properties',
  'env',
  'dotenv',
  'csv',
  'tsv',
  'tab',
  'log',
  'out',
  'diff',
  'patch',

  // Infrastructure/DevOps
  'tf',
  'tfvars',
  'hcl',
  'nomad',
  'dockerfile',
  'containerfile',
  'bicep',
  'azcli',
  'vagrantfile',
  'jenkinsfile',
  'helmfile',

  // Shell & Scripts
  'sh',
  'bash',
  'zsh',
  'fish',
  'ksh',
  'csh',
  'tcsh',
  'ash',
  'dash',
  'ps1',
  'psm1',
  'psd1',
  'ps1xml',
  'bat',
  'cmd',
  'btm',

  // Database
  'sql',
  'ddl',
  'dml',
  'mysql',
  'pgsql',
  'plsql',
  'plpgsql',
  'redis',
  'cql',
  'hql',
  'graphql',
  'gql',
  'prisma',
  'cypher',
  'sparql',
  'rq',

  // Template Engines
  'twig',
  'hbs',
  'handlebars',
  'mustache',
  'liquid',
  'ejs',
  'njk',
  'nunjucks',
  'jinja',
  'jinja2',
  'j2',
  'freemarker',
  'ftl',
  'razor',
  'cshtml',
  'vbhtml',
  'slim',
  'haml',
  'proto',
  'proto3',

  // Documentation & Markup
  'tex',
  'latex',
  'ltx',
  'sty',
  'bib',
  'bibtex',

  // Other/Specialized
  'apex',
  'trigger',
  'abap',
  'sb',
  'st',
  'pq',
  'pqm',
  'wgsl',
  'typespec',
  'tsp',
  'glsl',
  'vert',
  'frag',
  'geom',
  'comp',
  'hlsl',
  'fx',
  'fxh',
  'cg',
  'cu',
  'cuh',
  'cmake',
  'make',
  'makefile',
  'mk',
  'mak',
  'gnumakefile',
  'automake',
  'am',

  // Special files (dotfiles and config files)
  'gitignore',
  'gitattributes',
  'gitmodules',
  'editorconfig',
  'npmrc',
  'nvmrc',
  'babelrc',
  'eslintrc',
  'prettierrc',
  'stylelintrc',
  'browserslistrc',
  'htaccess',
  'htpasswd',
  'nginx',
  'caddyfile',
  'procfile',
  'gemfile',
  'rakefile',
  'podfile',
  'fastfile',
  'appfile',
  'brewfile',
  'berksfile',
  'guardfile',
  'puppetfile',
  'thorfile',
  'capfile',
  'jbuilder',
  'rabl',
  'podspec',
] as const;

export const MONACO_FILE_TYPE_OPTIONS: { label: string; value: string }[] = MONACO_EDITABLE_EXTENSIONS.map((ext) => ({
  label: `.${ext}`,
  value: ext,
}));

export const FILE_TYPE_LABELS: Record<string, string> = {
  // Documents
  PDF: 'PDF file',
  DOC: 'Word document',
  DOCX: 'Word document',
  XLS: 'Excel spreadsheet',
  XLSX: 'Excel spreadsheet',
  PPT: 'PowerPoint presentation',
  PPTX: 'PowerPoint presentation',
  ODT: 'OpenDocument text',
  ODS: 'OpenDocument spreadsheet',
  ODP: 'OpenDocument presentation',
  RTF: 'Rich text file',
  TXT: 'Text file',
  TEXT: 'Text file',
  CSV: 'CSV file',
  TSV: 'TSV file',
  TAB: 'Tab-separated file',

  // Code - Web (JavaScript/TypeScript)
  JS: 'JavaScript file',
  MJS: 'JavaScript module',
  CJS: 'CommonJS module',
  JSX: 'JSX file',
  TS: 'TypeScript file',
  MTS: 'TypeScript module',
  CTS: 'CommonJS TypeScript',
  TSX: 'TSX file',
  VUE: 'Vue file',
  SVELTE: 'Svelte file',
  ASTRO: 'Astro file',

  // Code - Web (Markup & Styles)
  HTML: 'HTML file',
  HTM: 'HTML file',
  XHTML: 'XHTML file',
  SHTML: 'Server-side HTML',
  CSS: 'CSS file',
  SCSS: 'SCSS file',
  SASS: 'Sass file',
  LESS: 'Less file',
  STYL: 'Stylus file',
  STYLUS: 'Stylus file',
  POSTCSS: 'PostCSS file',
  COFFEE: 'CoffeeScript file',
  LITCOFFEE: 'Literate CoffeeScript',
  PUG: 'Pug file',
  JADE: 'Jade file',

  // Code - Backend (Common)
  PY: 'Python file',
  PYW: 'Python script',
  PYI: 'Python stub file',
  PYX: 'Cython file',
  PXD: 'Cython declaration',
  RB: 'Ruby file',
  ERB: 'ERB template',
  RAKE: 'Rake file',
  GEMSPEC: 'Gem specification',
  PHP: 'PHP file',
  PHP3: 'PHP file',
  PHP4: 'PHP file',
  PHP5: 'PHP file',
  PHP7: 'PHP file',
  PHP8: 'PHP file',
  PHTML: 'PHP HTML file',
  PHPS: 'PHP source',
  JAVA: 'Java file',
  JSP: 'JSP file',
  JSPX: 'JSP XML file',
  KT: 'Kotlin file',
  KTS: 'Kotlin script',
  SWIFT: 'Swift file',
  GO: 'Go file',
  MOD: 'Go module',
  RS: 'Rust file',
  C: 'C file',
  H: 'C header',
  CPP: 'C++ file',
  CC: 'C++ file',
  CXX: 'C++ file',
  HPP: 'C++ header',
  HH: 'C++ header',
  HXX: 'C++ header',
  INO: 'Arduino file',
  CS: 'C# file',
  CSX: 'C# script',
  R: 'R file',
  RMD: 'R Markdown',
  RNW: 'R Noweb',
  SNW: 'Sweave file',
  RHTML: 'R HTML',
  SCALA: 'Scala file',
  SC: 'Scala script',
  SBT: 'SBT build file',
  GROOVY: 'Groovy file',
  GRADLE: 'Gradle file',
  GVY: 'Groovy file',
  GY: 'Groovy file',
  GSH: 'Groovy shell',

  // Code - Backend (Additional Languages)
  DART: 'Dart file',
  EX: 'Elixir file',
  EXS: 'Elixir script',
  EEX: 'EEx template',
  HEEX: 'HEEx template',
  LEEX: 'LEEx template',
  FS: 'F# file',
  FSI: 'F# script',
  FSX: 'F# script',
  FSSCRIPT: 'F# script',
  JL: 'Julia file',
  LUA: 'Lua file',
  M: 'Objective-C file',
  MM: 'Objective-C++ file',
  PAS: 'Pascal file',
  PP: 'Pascal file',
  INC: 'Include file',
  LPR: 'Lazarus project',
  DPR: 'Delphi project',
  PL: 'Perl file',
  PM: 'Perl module',
  POD: 'Perl documentation',
  T: 'Perl test',
  CLJ: 'Clojure file',
  CLJS: 'ClojureScript file',
  CLJC: 'Clojure common file',
  EDN: 'EDN file',
  SCM: 'Scheme file',
  SS: 'Scheme file',
  RKT: 'Racket file',
  TCL: 'Tcl file',
  TK: 'Tk file',
  VB: 'Visual Basic file',
  VBS: 'VBScript file',
  BAS: 'Basic file',
  FRM: 'VB Form',
  SOL: 'Solidity file',
  VY: 'Vyper file',
  QS: 'Q# file',
  V: 'Verilog file',
  SV: 'SystemVerilog file',
  SVH: 'SystemVerilog header',
  VHD: 'VHDL file',
  VHDL: 'VHDL file',
  ASM: 'Assembly file',
  S: 'Assembly file',
  HS: 'Haskell file',
  LHS: 'Literate Haskell',
  ERL: 'Erlang file',
  HRL: 'Erlang header',
  ML: 'OCaml file',
  MLI: 'OCaml interface',
  NIM: 'Nim file',
  NIMS: 'Nim script',
  NIMBLE: 'Nimble file',
  ZIG: 'Zig file',
  CR: 'Crystal file',
  D: 'D file',
  DI: 'D interface',
  ADA: 'Ada file',
  ADB: 'Ada body',
  ADS: 'Ada spec',
  F: 'Fortran file',
  F90: 'Fortran 90 file',
  F95: 'Fortran 95 file',
  F03: 'Fortran 2003 file',
  F08: 'Fortran 2008 file',
  FOR: 'Fortran file',
  FPP: 'Fortran preprocessor',
  COB: 'COBOL file',
  CBL: 'COBOL file',
  CPY: 'COBOL copybook',
  LISP: 'Lisp file',
  LSP: 'Lisp file',
  CL: 'Common Lisp file',
  EL: 'Emacs Lisp file',
  PROLOG: 'Prolog file',
  PRO: 'Prolog file',
  P: 'Prolog file',

  // Code - Config & Data
  JSON: 'JSON file',
  JSONC: 'JSON with comments',
  JSON5: 'JSON5 file',
  JSONL: 'JSON Lines file',
  NDJSON: 'Newline JSON',
  GEOJSON: 'GeoJSON file',
  YAML: 'YAML file',
  YML: 'YAML file',
  XML: 'XML file',
  XSD: 'XML Schema',
  XSL: 'XSL file',
  XSLT: 'XSLT file',
  DTD: 'DTD file',
  RSS: 'RSS feed',
  ATOM: 'Atom feed',
  PLIST: 'Property list',
  TOML: 'TOML file',
  INI: 'INI file',
  CFG: 'Config file',
  CONF: 'Config file',
  CONFIG: 'Config file',
  PROPERTIES: 'Properties file',
  ENV: 'Environment file',
  DOTENV: 'Dotenv file',
  LOG: 'Log file',
  OUT: 'Output file',
  DIFF: 'Diff file',
  PATCH: 'Patch file',

  // Infrastructure/DevOps
  TF: 'Terraform file',
  TFVARS: 'Terraform variables',
  HCL: 'HCL file',
  NOMAD: 'Nomad file',
  DOCKERFILE: 'Dockerfile',
  CONTAINERFILE: 'Containerfile',
  BICEP: 'Bicep file',
  AZCLI: 'Azure CLI file',
  VAGRANTFILE: 'Vagrantfile',
  JENKINSFILE: 'Jenkinsfile',
  HELMFILE: 'Helmfile',

  // Code - Shell & Scripts
  SH: 'Shell script',
  BASH: 'Bash script',
  ZSH: 'Zsh script',
  FISH: 'Fish script',
  KSH: 'Korn shell script',
  CSH: 'C shell script',
  TCSH: 'Tcsh script',
  ASH: 'Ash script',
  DASH: 'Dash script',
  PS1: 'PowerShell script',
  PSM1: 'PowerShell module',
  PSD1: 'PowerShell data',
  PS1XML: 'PowerShell XML',
  BAT: 'Batch file',
  CMD: 'Command file',
  BTM: 'Batch file',

  // Code - Database
  SQL: 'SQL file',
  DDL: 'DDL file',
  DML: 'DML file',
  MYSQL: 'MySQL file',
  PGSQL: 'PostgreSQL file',
  PLSQL: 'PL/SQL file',
  PLPGSQL: 'PL/pgSQL file',
  REDIS: 'Redis file',
  CQL: 'CQL file',
  HQL: 'HQL file',
  GRAPHQL: 'GraphQL file',
  GQL: 'GraphQL file',
  PRISMA: 'Prisma file',
  CYPHER: 'Cypher file',
  SPARQL: 'SPARQL file',
  RQ: 'SPARQL file',

  // Template Engines
  TWIG: 'Twig file',
  HBS: 'Handlebars file',
  HANDLEBARS: 'Handlebars file',
  MUSTACHE: 'Mustache file',
  LIQUID: 'Liquid file',
  EJS: 'EJS file',
  NJK: 'Nunjucks file',
  NUNJUCKS: 'Nunjucks file',
  JINJA: 'Jinja file',
  JINJA2: 'Jinja2 file',
  J2: 'Jinja2 file',
  FREEMARKER: 'FreeMarker file',
  FTL: 'FreeMarker file',
  RAZOR: 'Razor file',
  CSHTML: 'Razor C# file',
  VBHTML: 'Razor VB file',
  SLIM: 'Slim file',
  HAML: 'Haml file',
  PROTO: 'Protocol Buffers file',
  PROTO3: 'Protocol Buffers 3',

  // Markdown & Docs
  MD: 'Markdown file',
  MDX: 'MDX file',
  MARKDOWN: 'Markdown file',
  MDOWN: 'Markdown file',
  MKD: 'Markdown file',
  MKDN: 'Markdown file',
  RST: 'reStructuredText file',
  REST: 'reStructuredText file',
  TEX: 'LaTeX file',
  LATEX: 'LaTeX file',
  LTX: 'LaTeX file',
  STY: 'LaTeX style',
  BIB: 'BibTeX file',
  BIBTEX: 'BibTeX file',
  ORG: 'Org file',
  ADOC: 'AsciiDoc file',
  ASCIIDOC: 'AsciiDoc file',
  ASC: 'AsciiDoc file',

  // Other/Specialized
  APEX: 'Apex file',
  TRIGGER: 'Apex trigger',
  ABAP: 'ABAP file',
  SB: 'Small Basic file',
  ST: 'Structured Text file',
  PQ: 'Power Query file',
  PQM: 'Power Query file',
  WGSL: 'WGSL file',
  TYPESPEC: 'TypeSpec file',
  TSP: 'TypeSpec file',
  GLSL: 'GLSL shader',
  VERT: 'Vertex shader',
  FRAG: 'Fragment shader',
  GEOM: 'Geometry shader',
  COMP: 'Compute shader',
  HLSL: 'HLSL shader',
  FX: 'Effect file',
  FXH: 'Effect header',
  CG: 'Cg shader',
  CU: 'CUDA file',
  CUH: 'CUDA header',
  CMAKE: 'CMake file',
  MAKE: 'Makefile',
  MAKEFILE: 'Makefile',
  MK: 'Makefile',
  MAK: 'Makefile',
  GNUMAKEFILE: 'GNU Makefile',
  AUTOMAKE: 'Automake file',
  AM: 'Automake file',

  // Special files (dotfiles and config)
  GITIGNORE: 'Git ignore file',
  GITATTRIBUTES: 'Git attributes',
  GITMODULES: 'Git submodules',
  EDITORCONFIG: 'EditorConfig file',
  NPMRC: 'npm config',
  NVMRC: 'nvm config',
  BABELRC: 'Babel config',
  ESLINTRC: 'ESLint config',
  PRETTIERRC: 'Prettier config',
  STYLELINTRC: 'Stylelint config',
  BROWSERSLISTRC: 'Browserslist config',
  HTACCESS: 'Apache config',
  HTPASSWD: 'Apache passwords',
  NGINX: 'Nginx config',
  CADDYFILE: 'Caddy config',
  PROCFILE: 'Procfile',
  GEMFILE: 'Gemfile',
  RAKEFILE: 'Rakefile',
  PODFILE: 'Podfile',
  FASTFILE: 'Fastfile',
  APPFILE: 'Appfile',
  BREWFILE: 'Brewfile',
  BERKSFILE: 'Berksfile',
  GUARDFILE: 'Guardfile',
  PUPPETFILE: 'Puppetfile',
  THORFILE: 'Thorfile',
  CAPFILE: 'Capfile',
  JBUILDER: 'Jbuilder file',
  RABL: 'RABL file',
  PODSPEC: 'CocoaPods spec',
  LOCK: 'Lock file',
  LICENSE: 'License file',

  // Images
  PNG: 'PNG image',
  JPG: 'JPEG image',
  JPEG: 'JPEG image',
  GIF: 'GIF image',
  WEBP: 'WebP image',
  BMP: 'Bitmap image',
  ICO: 'Icon file',
  SVG: 'SVG image',
  PSD: 'Photoshop file',
  AI: 'Illustrator file',
  EPS: 'EPS file',
  FIG: 'Figma file',
  SKETCH: 'Sketch file',
  XD: 'Adobe XD file',

  // Video
  MP4: 'MP4 video',
  MOV: 'QuickTime video',
  AVI: 'AVI video',
  MKV: 'MKV video',
  WEBM: 'WebM video',
  WMV: 'WMV video',
  FLV: 'Flash video',
  M4V: 'M4V video',

  // Audio
  MP3: 'MP3 audio',
  WAV: 'WAV audio',
  FLAC: 'FLAC audio',
  AAC: 'AAC audio',
  M4A: 'M4A audio',
  OGG: 'OGG audio',
  WMA: 'WMA audio',
  AIFF: 'AIFF audio',
  MID: 'MIDI file',
  MIDI: 'MIDI file',

  // Archives
  ZIP: 'ZIP archive',
  RAR: 'RAR archive',
  '7Z': '7-Zip archive',
  TAR: 'TAR archive',
  GZ: 'Gzip archive',
  BZ2: 'Bzip2 archive',
  XZ: 'XZ archive',

  // Fonts
  TTF: 'TrueType font',
  OTF: 'OpenType font',
  WOFF: 'Web font',
  WOFF2: 'Web font',
  EOT: 'Embedded font',

  // Executables
  EXE: 'Windows executable',
  MSI: 'Windows installer',
  DMG: 'macOS disk image',
  APP: 'macOS application',
  DEB: 'Debian package',
  RPM: 'RPM package',
  APK: 'Android package',
  IPA: 'iOS application',

  // 3D & CAD
  OBJ: '3D object file',
  FBX: 'FBX file',
  STL: 'STL file',
  GLTF: 'glTF file',
  GLB: 'GLB file',
  BLEND: 'Blender file',
  DWG: 'AutoCAD file',

  // Ebooks
  EPUB: 'EPUB ebook',
  MOBI: 'Kindle ebook',
  AZW: 'Kindle ebook',
};
