import { ICON_SPRITE_TYPES } from '@zamp-platform/ui/types';

export const USERS_ICONS: Record<string, ICON_SPRITE_TYPES> = {
  'face-content': ICON_SPRITE_TYPES.USERS,
  'user-check-02': ICON_SPRITE_TYPES.USERS,
  'user-right-01': ICON_SPRITE_TYPES.USERS,
  'face-frown': ICON_SPRITE_TYPES.USERS,
  'user-circle': ICON_SPRITE_TYPES.USERS,
  'user-right-02': ICON_SPRITE_TYPES.USERS,
  'face-happy': ICON_SPRITE_TYPES.USERS,
  'user-down-01': ICON_SPRITE_TYPES.USERS,
  'user-square': ICON_SPRITE_TYPES.USERS,
  'face-neutral': ICON_SPRITE_TYPES.USERS,
  'user-down-02': ICON_SPRITE_TYPES.USERS,
  'user-up-01': ICON_SPRITE_TYPES.USERS,
  'face-sad': ICON_SPRITE_TYPES.USERS,
  'user-edit': ICON_SPRITE_TYPES.USERS,
  'user-up-02': ICON_SPRITE_TYPES.USERS,
  'face-smile': ICON_SPRITE_TYPES.USERS,
  'user-left-01': ICON_SPRITE_TYPES.USERS,
  'user-x-01': ICON_SPRITE_TYPES.USERS,
  'face-wink': ICON_SPRITE_TYPES.USERS,
  'user-left-02': ICON_SPRITE_TYPES.USERS,
  'user-x-02': ICON_SPRITE_TYPES.USERS,
  'user-01': ICON_SPRITE_TYPES.USERS,
  'user-minus-01': ICON_SPRITE_TYPES.USERS,
  'users-01': ICON_SPRITE_TYPES.USERS,
  'user-02': ICON_SPRITE_TYPES.USERS,
  'user-minus-02': ICON_SPRITE_TYPES.USERS,
  'users-02': ICON_SPRITE_TYPES.USERS,
  'user-03': ICON_SPRITE_TYPES.USERS,
  'user-plus-01': ICON_SPRITE_TYPES.USERS,
  'user-plus-02': ICON_SPRITE_TYPES.USERS,
  'users-check': ICON_SPRITE_TYPES.USERS,
};
