export enum ACTIVITY_RUN_STATUS {
  NEEDS_ATTENTION = 'NEEDS_ATTENTION',
  VOID = 'VOID',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  DONE = 'DONE',
  FAILED = 'FAILED',
}

export type ArtifactType = {
  id: string;
  title: string;
  type: string;
}[];

export enum ARTIFACT_TYPE {
  PDF_DATASET = 'PDF_DATASET',
  EMAIL = 'EMAIL',
  BROWSER = 'BROWSER',
  EXTERNAL_LINK = 'EXTERNAL_LINK',
}

export enum LOG_STATUS {
  LOADING = 'INITIATED',
  MESSAGE_FROM_ADAM = 'MESSAGE_FROM_ADAM',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  NEEDS_ATTENTION = 'NEEDS_ATTENTION',
  VOID = 'VOID',
  DONE = 'DONE',
  MESSAGE_FROM_USER = 'MESSAGE_FROM_HUMAN',
}

export enum SENDER_TYPE {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
}

export enum CONTENT_TYPE {
  MESSAGE_SECTION = 'MESSAGE_SECTION',
  REPLIED_TO_SECTION = 'REPLIED_TO_SECTION',
}

export enum DATE_SEPARATOR {
  TODAY = 'TODAY',
  YESTERDAY = 'YESTERDAY',
  OTHER = 'OTHER',
}

export enum CTA_COMPONENT_TYPE {
  ARTIFACT = 'ARTIFACT',
  BUTTON = 'BUTTON',
}

export enum PDF_DATASET_TAB {
  DATASET = 'DATASET',
  PDF = 'PDF',
}

export enum CTA_ACTION {
  NONE = 'NONE',
  VIEW_EMAIL = 'VIEW_EMAIL',
  VIEW_DATASET_PDF_PDF_FIRST = 'VIEW_DATASET_PDF_PDF_FIRST',
  VIEW_DATASET_PDF_DATASET_FIRST = 'VIEW_DATASET_PDF_DATASET_FIRST',
  VIEW_EXTERNAL_REDIRECTION = 'VIEW_EXTERNAL_REDIRECTION',
  VIEW_INLINE_MEDIA = 'VIEW_INLINE_MEDIA',
}

export enum EMAIL_STATUS {
  DRAFT = 'DRAFT',
  RECEIVED = 'RECEIVED',
}
