global:
  service:
    name: application-platform-frontend-prd

projectName: zamp  # required
default:
  annotations:
    all:
      app.kv.io/env: prd
  labels:
    all:
      service-name: application-platform-frontend-svc
  resources:
    request:
      cpu: 500m
      memory: 512Mi
    limit:
      cpu: 1000m
      memory: 1024Mi
  replicaCount: 1
  image:
    repository: 
    tag: 
    imagePullPolicy: Always
  signoz:
    enabled: false
  configMaps:
    injection:
      enabled: false
    volumeMount:
      enabled: false
  externalSecrets:
    injection:
      enabled: false
    volumeMount:
      enabled: true
      secrets:
      - data:  
          - fileName: ".env"
            mountPath: "/home/node/app/.env"
            secretKey: zamp-prd-us-application-platform-frontend-env
        refreshInterval: 1h
        secretStoreName: aws-secrets-manager
        secretName: env
deployment:
  - name: "svc"
    labels:
      app.kubernetes.io/component: genesis
    service:
      type: ClusterIP
      ports:
      - port: 3000
        name: api
    serviceAccount:
        create: false
    terminationGracePeriodSeconds: 140
    containers:
      - name: "svc"
        port: 3000
        healthcheck: 
          enabled: true
          livenessProbe: 
            path : "/"
            initialDelaySeconds : 40
            periodSeconds: 30
          readinessProbe: 
            path : "/"
            initialDelaySeconds : 30
            periodSeconds : 30
        command:
        - npm
        args:
        - run
        - start
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 120
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 80 