global:
  service:
    name: application-platform-frontend-prd-us

projectName: zamp # required
serviceName: application-platform-frontend
default:
  annotations:
    all:
      app.kv.io/env: prd-us
  labels:
    all:
      service-name: application-platform-frontend-svc
  resources:
    request:
      cpu: 600m # Increased for US scale
      memory: 600Mi # Increased for US scale
    limit:
      cpu: 1200m # Increased for US scale
      memory: 1200Mi # Increased for US scale
  replicaCount: 3 # Increased for US scale
  image:
    repository: 916079538338.dkr.ecr.us-east-1.amazonaws.com/zamp-prd-us-application-platform-frontend-ecr
    tag: v1
    imagePullPolicy: Always
  signoz:
    enabled: false
  configMaps:
    injection:
      enabled: false
    volumeMount:
      enabled: false
  externalSecrets:
    injection:
      enabled: false
    volumeMount:
      enabled: false
deployment:
  - name: "svc"
    rollingUpdate:
      maxSurge: "1"
      maxUnavailable: "0"
    labels:
      app.kubernetes.io/component: genesis
    service:
      type: ClusterIP
      ports:
        - port: 3000
          name: api
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::916079538338:role/zamp-prd-us-application-platform-frontend-irsa-access-role
    containers:
      - name: "svc"
        port: 3000
        env:
          NODE_ENV: "production"
          NEXT_PUBLIC_ENVIRONMENT: "production"
    autoscaling:
      enabled: true
      minReplicas: 3 # Increased for US scale
      maxReplicas: 8 # Increased for US scale
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 75
